"""SAT Reading and Writing benchmark, Module 2 (27 questions, harder)."""
from bench_rw_common import E

M2 = [
    # ---- Craft and Structure
    E(2, 'words_in_context', 'hard', 'precise word in context',
      'Though the novelist’s early reviews were largely _____, recording her books’ plots and settings without evaluating their merit, later critics approached her work with far more analytical rigor, examining its structure, its themes, and its place in the tradition she inherited.',
      'descriptive', ['dismissive', 'enthusiastic', 'derivative'],
      'Reviews that record plots and settings “without evaluating their merit” are descriptive. “Dismissive” and “enthusiastic” would be evaluations, and “derivative” refers to the books’ originality, not the style of the reviews.'),
    E(2, 'words_in_context', 'hard', 'precise word in context',
      'Geologist Kwame Mensah cautions that the _____ of the fossil record can skew our picture of ancient life. Soft-bodied organisms rarely fossilize, so ecosystems that were once rich with such creatures appear, in stone, deceptively sparse.',
      'incompleteness', ['abundance', 'precision', 'popularity'],
      'The record omits soft-bodied organisms, making ecosystems look “deceptively sparse,” so its incompleteness is what skews the picture. Abundance and precision would not produce a misleadingly sparse picture.'),
    E(2, 'words_in_context', 'hard', 'precise word in context',
      'The mayor’s remarks were intentionally _____: rather than commit to either the housing plan or the transit plan, she praised the goals of both and promised only that the council would continue to study them. Reporters who asked for a firm position left the press conference without one.',
      'equivocal', ['adamant', 'effusive', 'belligerent'],
      'She avoided committing and offered no firm position, which is deliberately ambiguous, or equivocal. Adamant means unyielding. Effusive and belligerent describe warmth and hostility, which the text does not show.'),
    E(2, 'text_structure_purpose', 'hard', 'function of a sentence',
      'The following text is adapted from a novel. Every Sunday, Teodoro climbed the ridge behind his house to tend the beehives his father had left him. [underlined: He hummed to the bees, as his father had, though he never told anyone that the tune was one he had invented after the funeral.] The hives thrived that year, and neighbors who had once teased him for his patience began to ask for jars of honey.',
      'It reveals a private act of remembrance that adds emotional depth to a routine task.',
      ['It introduces a conflict between Teodoro and his neighbors.', 'It explains why the hives thrived during the year described.', 'It suggests that Teodoro is embarrassed by his father’s legacy.'],
      'The sentence discloses a hidden, personal detail: Teodoro’s own tune, made after his father’s funeral. That gives the ordinary chore emotional weight. The text never links the humming to the hives’ success, and nothing signals embarrassment.',
      stem='Which choice best describes the function of the underlined sentence in the text as a whole?'),
    E(2, 'text_structure_purpose', 'hard', 'main purpose',
      'In 2019, a team led by oceanographer Priya Desai deployed forty floating sensors to track how heat moves through the deep Atlantic. Earlier models had assumed that heat spreads evenly with depth. Desai’s sensors revealed instead that warm water collects in thin, distinct layers that can persist for months. The finding does not overturn the earlier models, but it suggests that they overlook structure that may affect how quickly the ocean absorbs heat.',
      'To describe a research finding and explain how it qualifies an assumption of earlier models.',
      ['To argue that earlier models of ocean heat should be abandoned.', 'To explain how ocean sensors are designed and deployed.', 'To compare the Atlantic with other oceans.'],
      'The text reports what the sensors found and says the finding “does not overturn” earlier models but shows they overlook layering. That is qualification, not rejection. Sensor design and other oceans are never discussed.',
      stem='Which choice best states the main purpose of the text?'),
    E(2, 'cross_text_connections', 'hard', 'response to a claim',
      'Text 1\nA historian argues that ancient Roman roads are misunderstood as instruments of conquest. Most of the network, she claims, was financed by local communities for their own trade, and military columns made up only a small fraction of the traffic that used it.\n\nText 2\nAn archaeologist points to inscriptions showing that the Roman army surveyed and built the major arteries of the network. Merchants and towns later extended it with smaller branch roads. Claims that the network was mainly commercial, he argues, overlook this sequence.',
      'As an overstatement that fails to acknowledge the army’s role in building the main roads.',
      ['As accurate in describing who paid for every road in the network.', 'As mistaken in asserting that any military traffic used the roads.', 'As consistent with inscriptions showing local funding of the main roads.'],
      'Text 2’s author says the army built the major arteries and that commercial claims overlook this. He would therefore see Text 1 as neglecting the army’s role. He does not deny that some roads were locally funded, and the inscriptions he cites concern military construction.',
      stem='Based on the texts, how would the author of Text 2 most likely characterize the claim in Text 1?'),
    E(2, 'cross_text_connections', 'medium', 'relationship between texts',
      'Text 1\nSome nutrition researchers argue that studies linking a daily glass of red wine to heart health reflect a real benefit of compounds found in grapes. They note that the effect appears in studies from several countries and that laboratory experiments have shown the compounds to reduce inflammation in animal cells.\n\nText 2\nA team reanalyzed those studies and found that moderate drinkers tended to be wealthier and to exercise more than people who abstained. When the researchers adjusted for income and exercise, the apparent benefit largely vanished, and the remaining difference between drinkers and abstainers was too small to rule out chance.',
      'Text 2 offers an alternative explanation for the evidence cited in Text 1.',
      ['Text 2 replicates the findings described in Text 1.', 'Text 2 provides a definition of a term used in Text 1.', 'Text 2 gives an example of the benefit claimed in Text 1.'],
      'Text 2 accepts the association but attributes it to income and exercise, which is an alternative explanation. It does not replicate the benefit, define terms, or illustrate the claimed benefit.',
      stem='Which choice best describes the relationship between the two texts?'),
    # ---- Information and Ideas
    E(2, 'central_ideas', 'hard', 'main idea',
      'When a river is dammed, its downstream ecosystems change in ways that engineers did not always anticipate. In the Oru River basin, the dam trapped sediment that once fertilized floodplain farms, and cold water released from the reservoir altered the life cycles of native fish. Yet the dam also ended seasonal floods that had destroyed villages. Planners now weigh these competing effects as they revise the dam’s release schedule.',
      'The dam’s effects on the Oru River basin have been both harmful and beneficial, which complicates decisions about how it should be operated.',
      ['Engineers failed to anticipate any of the dam’s consequences for the basin.', 'The dam should be removed so that the river can return to its former state.', 'Seasonal floods were the most serious danger that villages in the basin faced.'],
      'The text lists damaging effects and a benefit, then says planners weigh them. The other choices overstate (“any”), prescribe removal, or elevate one detail above the whole.'),
    E(2, 'central_ideas', 'hard', 'main idea',
      'The following text is adapted from an essay. As a child, I believed the village clock was wrong because it never agreed with my father’s watch. Only as an adult did I learn that the clock, installed by the old postmaster, had been set deliberately seven minutes fast so that no one would miss the morning bus. The discovery pleased me more than it should have: it revealed that someone, long ago, had quietly accounted for our lateness.',
      'A narrator recalls a childhood puzzle and finds that its resolution reveals others’ thoughtful consideration.',
      ['A village clock was less accurate than a wristwatch because it was old.', 'A narrator’s father repeatedly corrected the narrator’s misunderstandings about time.', 'A narrator resents the postmaster for having set a clock incorrectly.'],
      'The narrator resolves an old puzzle and is pleased to find that someone had planned for villagers’ lateness. The clock was set fast on purpose, the father’s role is minor, and the narrator feels pleasure, not resentment.'),
    E(2, 'command_of_evidence_text', 'hard', 'weaken a hypothesis',
      'Marine biologists propose that the bright patterns on certain sea slugs warn predators that the slugs are toxic. The slugs are slow-moving and have no shells, and their bodies contain chemicals that taste bitter to fish. The biologists argue that predators that encounter a brightly patterned slug learn to associate the pattern with the unpleasant taste and then avoid similar slugs in the future.',
      'In laboratory trials, predators ate brightly patterned slugs as readily as drab ones and showed no signs of illness afterward.',
      ['The patterns vary in color from one slug to another.', 'Some predators learned to avoid the brightly patterned slugs after one bad experience.', 'The toxin in the slugs is produced by algae that the slugs eat.'],
      'If predators eat the patterned slugs without harm or hesitation, the patterns are not functioning as warnings of toxicity, which weakens the proposal. Variation in color and the toxin’s source are irrelevant, and learned avoidance supports the proposal.',
      stem='Which finding, if true, would most directly weaken the biologists’ proposal?'),
    E(2, 'command_of_evidence_text', 'hard', 'quotation that illustrates a claim',
      'In the poem “Night Tram,” the speaker rides through a city after dark, observing the lit windows of apartments, the last commuters hurrying home, and the river glinting beside the tracks. The poem never states outright how the speaker feels about the place. A critic argues that the speaker’s feelings about the city are ambivalent, combining affection with a wish to escape.',
      '“I love the lit windows and the hurry, and I count the hours until I can leave them.”',
      ['“The tram hums along the river, past shuttered shops and sleeping doors.”', '“I have lived here thirty years and know every lamp by name.”', '“Each night the city swallows the last of the light, and I watch it go.”'],
      'Ambivalence requires both affection (“I love”) and a wish to leave (“count the hours”). The other quotations convey description, familiarity, or a mood but not both conflicting feelings.',
      stem='Which quotation from the poem most effectively illustrates the critic’s claim?'),
    E(2, 'command_of_evidence_quant', 'hard', 'use data to support a claim',
      'A beekeeping association claims that although the number of colonies in the state declined between 2010 and 2020, the average yield per colony increased.\n\n| Year | Colonies (thousands) | Honey per colony (pounds) |\n|---|---|---|\n| 2010 | 120 | 52 |\n| 2015 | 110 | 58 |\n| 2020 | 100 | 66 |',
      'From 2010 to 2020, the number of colonies fell from 120 thousand to 100 thousand, but the honey produced per colony rose from 52 pounds to 66 pounds.',
      ['Honey per colony rose from 52 pounds in 2010 to 58 pounds in 2015.', 'The state had 100 thousand colonies in 2020, the lowest number among the years shown.', 'The number of colonies declined from 120 thousand in 2010 to 110 thousand in 2015.'],
      'The claim has two parts: colonies declined while yield per colony rose. Only the correct choice gives both trends over the full period. Each other choice gives one part or a shorter period.',
      stem='Which choice most effectively uses data from the table to support the association’s claim?'),
    E(2, 'command_of_evidence_quant', 'hard', 'use data to support a claim',
      'A botanist tested how soil temperature affects the germination of a wildflower and concluded that germination is most successful at a moderate temperature and drops when the soil becomes warmer than optimal.\n\n| Soil temperature | Seeds that germinated |\n|---|---|\n| 10°C | 22% |\n| 15°C | 61% |\n| 20°C | 84% |\n| 25°C | 47% |',
      'Germination peaked at 84% at 20°C but fell to 47% at 25°C.',
      ['Germination rose from 22% at 10°C to 61% at 15°C.', 'Germination was 22% at 10°C and 47% at 25°C.', 'Germination was higher at 20°C than at 10°C.'],
      'The conclusion has a peak and a decline past it. Only the correct choice shows the highest rate and the drop at the warmer temperature. The others show only a rise or compare points that do not show the peak-and-decline pattern.',
      stem='Which choice most effectively uses data from the table to support the botanist’s conclusion?'),
    E(2, 'inferences', 'hard', 'logical completion',
      'Linguists have long observed that children who begin learning a second language in early childhood typically speak it without a foreign accent, whereas those who begin in adolescence rarely do. A recent study, however, found that adults who received intensive training in distinguishing the sounds of a new language before attempting to speak it achieved accents nearly indistinguishable from those of native speakers. This finding suggests that _____',
      'the difficulty adults have with accents may stem in part from how they learn sounds rather than from age alone.',
      ['age has no effect on a person’s ability to learn a second language.', 'adults who start a second language late cannot overcome a foreign accent.', 'children learn the sounds of a new language by the same training method the adults used.'],
      'Adults with special sound training achieved native-like accents, so method matters along with age. The study does not show that age has no effect, contradicts the claim that accents cannot be overcome, and says nothing about how children learn.'),
    # ---- Standard English Conventions
    E(2, 'boundaries', 'hard', 'nonessential clause punctuation',
      'The novelist’s final book, which took her eleven years to complete _____ was published posthumously and quickly became her best-selling work, prompting critics to reassess the decade she spent writing it.',
      ',', [';', '—', ':'],
      'The clause beginning “which” is nonessential and opened with a comma after “book,” so it must close with a comma. A semicolon, dash, or colon would mismatch the opening punctuation.'),
    E(2, 'boundaries', 'medium', 'dependent clause followed by a main clause',
      'Although the trail had been closed since March because of mudslides and fallen timber _____ a few hikers ignored the posted warnings and set out anyway.',
      ',', [';', ':', '.'],
      'The “although” clause is dependent, so it needs a comma before the main clause. A semicolon, colon, or period would separate a dependent clause from the clause that completes it, creating a fragment.'),
    E(2, 'subject_verb_agreement', 'hard', 'agreement with an interrupting phrase',
      'The results of the survey, along with the comments that respondents added in the open-ended section, _____ that the town’s residents want more evening bus service.',
      'suggest', ['suggests', 'has suggested', 'is suggesting'],
      'The subject is the plural “results”; “along with the comments” does not change its number. The plural verb “suggest” agrees. The other choices are singular.'),
    E(2, 'pronouns_modifiers', 'medium', 'pronoun-antecedent agreement',
      'When a company introduces a new product, _____ usually surveys potential customers first, because early feedback can prevent costly design mistakes that would be difficult to correct after production begins.',
      'it', ['they', 'one', 'we'],
      'The antecedent “a company” is singular, so the pronoun must be “it.” “They” is plural, and “one” or “we” introduce an inappropriate person.'),
    E(2, 'verb_tense', 'medium', 'past perfect for an earlier period',
      'Before she was appointed director in 2015, Dr. Hale _____ for nine years in the institute’s genetics lab, where she developed techniques that are still in use.',
      'had worked', ['has worked', 'is working', 'will work'],
      'Her lab work came before the appointment in 2015, another past event, so the past perfect “had worked” is required. Present-perfect, present-progressive, and future forms conflict with the timeline.'),
    E(2, 'form_structure_sense', 'medium', 'its versus it’s',
      'The orchestra’s decision to extend _____ season by two weeks surprised many subscribers, who had already arranged their summer plans around the original schedule.',
      'its', ['it’s', 'it', 'its’'],
      '“Its” is the possessive form modifying “season.” “It’s” means “it is” or “it has,” “it” is not possessive, and “its’” is not a word.'),
    E(2, 'form_structure_sense', 'medium', 'whose versus who’s',
      'The research team, _____ findings were published in a leading journal last spring, has received a grant to expand its work to three additional sites.',
      'whose', ['who’s', 'which', 'whom'],
      'The word must show possession of “findings,” which is the job of “whose.” “Who’s” means “who is,” and “which” and “whom” do not express possession.'),
    # ---- Expression of Ideas
    E(2, 'transitions', 'hard', 'expectation versus result',
      'The botanist had predicted that the seeds would fail to sprout in the salty soil. _____ several of them sprouted within a week, prompting her to reconsider how tolerant the species might be.',
      'Instead,', ['Therefore,', 'Similarly,', 'Meanwhile,'],
      'The second sentence reports what actually happened in place of the predicted failure, which “Instead” signals. “Therefore” and “Similarly” imply a result or likeness the text does not show, and “Meanwhile” signals simultaneity.'),
    E(2, 'transitions', 'hard', 'concession',
      'Nutrition labels list the amount of added sugar in a serving. _____ many consumers do not realize that a single bottle can contain several servings, which multiplies the sugar they actually consume.',
      'Even so,', ['For example,', 'As a result,', 'In other words,'],
      'Despite the labeling just described, consumers still misjudge their intake; “Even so” signals that concession. The other transitions introduce an example, a consequence, or a restatement.'),
    E(2, 'transitions', 'hard', 'contrast between groups',
      'Early critics of the novel complained that its long digressions slowed the story. _____ later readers have come to regard those digressions as the book’s greatest strength, since they build the world in which the characters act.',
      'By contrast,', ['As a result,', 'In addition,', 'For this reason,'],
      'The sentence sets later readers’ opinion against early critics’, a contrast of groups. The other transitions signal consequence, addition, or reasoning that the text does not support.'),
    E(2, 'rhetorical_synthesis', 'hard', 'overview of a work',
      'Notes:\n• Lena Brandt (1921–2004) was a Dutch-born Canadian novelist.\n• Her first novel, The Quiet Harbor, was published in 1958.\n• The novel follows a family of fishers in Nova Scotia.\n• Critics praised it for its spare prose.\n• It has been translated into 11 languages.',
      'Lena Brandt’s first novel, The Quiet Harbor (1958), follows a family of fishers in Nova Scotia and was praised for its spare prose.',
      ['Lena Brandt was a Dutch-born Canadian novelist who lived from 1921 to 2004.', 'The Quiet Harbor has been translated into 11 languages.', 'Critics praised spare prose in all of Brandt’s novels.'],
      'The goal is an overview of the first novel, so the sentence should cover its title, date, subject, and reception. The other choices describe the author, a single fact, or make a claim about “all” of her novels that the notes do not support.',
      stem='The student wants to provide an overview of Brandt’s first novel for readers unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
    E(2, 'rhetorical_synthesis', 'hard', 'emphasize a similarity',
      'Notes:\n• The Kaveri River in India and the Hudson River in New York both feed major estuaries.\n• Both rivers were heavily polluted by industry in the 20th century.\n• Cleanup programs on both rivers began in the 1970s.\n• The Kaveri program focused on wastewater treatment.\n• The Hudson program focused on regulating industrial discharge.',
      'Both the Kaveri and the Hudson were heavily polluted by industry in the 20th century, and cleanup programs for both began in the 1970s.',
      ['The Kaveri’s cleanup focused on wastewater treatment, whereas the Hudson’s focused on regulating industrial discharge.', 'The Kaveri River is in India, and the Hudson River is in New York.', 'Both rivers feed major estuaries.'],
      'The goal is a similarity in the rivers’ recent histories: industrial pollution and cleanups beginning in the same decade. The other choices emphasize differences or describe geography rather than history.',
      stem='The student wants to emphasize a similarity between the two rivers’ recent histories. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
    E(2, 'rhetorical_synthesis', 'hard', 'finding with a limitation',
      'Notes:\n• Researchers studied 300 hospital patients recovering from knee surgery.\n• Half the patients had a plant in their room; half did not.\n• Patients with plants asked for less pain medication on average.\n• The difference was about 12 percent.\n• The researchers caution that the study was conducted at a single hospital.',
      'Patients recovering from knee surgery who had a plant in their room asked for about 12 percent less pain medication, though the study was conducted at a single hospital.',
      ['Researchers studied 300 hospital patients, half of whom had a plant in their room.', 'Patients with plants asked for less pain medication, a difference of about 12 percent.', 'The study was conducted at a single hospital, so its results are not reliable.'],
      'The goal has two parts: present the finding and acknowledge a limitation. Only the correct choice does both without overstating. The others give the design only, the finding only, or declare the results unreliable, which the notes do not say.',
      stem='The student wants to present the study’s finding while acknowledging a limitation. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
]
