"""ACT Reading benchmark: four passages, nine questions each (questions 51-86).

All passages are original. Correct choice first; the bank shuffles them.
"""
from bench_rw_common import E

SKILL = 'act_reading_detail'
HINTS = ['Return to the passage and find the lines the question points to before reading the choices.',
         'Match each choice to what the text actually says; eliminate any that add, exaggerate or reverse the claim.',
         'Choose the answer that can be supported by a specific sentence, not one that only sounds reasonable.']
NOTES = ['Is not supported by the passage.', 'Exaggerates or distorts a detail from the passage.', 'Describes something the passage mentions but answers a different question.']


def R(n, diff, sub, stem, correct, wrong, why):
    return {'skill_key': SKILL, 'subskill': sub, 'difficulty': diff, 'module': 2, 'number': n,
            'question_text': f'Question {n}. {stem}', 'options': [correct] + list(wrong), 'correct_option': 0,
            'explanation': why, 'hints': HINTS, 'strategy': HINTS[1], 'fastest_method': HINTS[2],
            'misconceptions': [''] + NOTES, 'validation': 'reviewed_bank'}


P1 = """LITERARY NARRATIVE: This passage is an original short story.

Every morning at seven, Ilse Brandt unlocked the shutters of her shop on Calloway Lane and lit the small lamp above her workbench. The shop smelled of oil and brass and old wood, and the walls were crowded with clocks of every description: tall case clocks standing like sentries, carriage clocks no bigger than a fist, and a cuckoo clock whose bird had not emerged in a decade. Most of them did not keep the same time. Ilse did not mind. She had long ago decided that a room full of disagreeing clocks was an honest room.

Customers came in with a particular kind of expression, the look of people carrying a small grief. A clock had stopped, a wedding gift or a dead uncle’s pocket watch, and with it, somehow, something else. Ilse never hurried them. She would turn the clock over in her hands, listen to it with her eyes half closed as though it were telling her a secret, and then say, “Come back Thursday.” It was always Thursday. Her assistant, a teenager named Dev who had taken the job to earn money for a used bicycle, had once asked why.

“Because nobody believes a repair that takes an hour,” she said. “They think I’ve done nothing. On Thursday, they believe me.”

Dev had laughed, but privately he thought this was the sort of thing people said when they wanted to seem wise. He had little patience for mystery. He liked the clocks that could be fixed by replacing a spring, and he was impatient with the ones that required Ilse’s long, silent listening. In his third month at the shop, he said so.

“You could be twice as fast,” he told her, “if you just tested the parts one at a time.”

Ilse looked at him over her glasses. She did not seem offended. She reached under the counter and set before him a small silver watch with a cracked crystal. “Then fix that,” she said. “Today. I will not say a word.”

It took him four hours. He replaced the mainspring, cleaned the gears, and adjusted the balance wheel until the watch ticked steadily in his palm. He held it up, triumphant, and Ilse nodded and said it was excellent work. Then she asked him to set it beside the carriage clock on the shelf and wait.

By evening the watch had lost six minutes. Dev frowned, opened it again, and found nothing wrong. He adjusted it, closed it, and watched it fall behind again over the next hour. The watch was not broken. Each part was sound. But something in how the parts lived together was off, a tiny drag he could not locate by testing pieces in isolation.

“You see,” Ilse said quietly, without any trace of triumph, “the parts are not the clock.”

She showed him how to hold the watch against his ear and to wait, without thinking of the parts, until the rhythm told him where it stumbled. It took him a week of Thursdays to hear it: a faint hesitation, like a person catching their breath on a stair. When he finally corrected it, a hairline burr on a single tooth, he felt something he had not expected. It was not pride, exactly. It was closer to the feeling of being let into a room he had walked past for years.

The following Thursday, a man in a gray coat came in holding his late wife’s mantel clock, and Dev was the one who said, “Come back on Thursday.” Ilse, at her bench, did not look up, but she smiled into the lamplight."""

Q1 = [
    R(51, 'easy', 'main idea', 'Which choice best describes what the passage is mainly about?', 'A young assistant comes to appreciate the patient, attentive way a clock repairer works.', ['A repairer discovers that her assistant has been neglecting the clocks in her shop.', 'A customer learns why some clocks are more difficult to repair than others.', 'An assistant replaces his employer’s methods with faster ones.'], 'The passage follows Dev from impatience with Ilse’s method to adopting it himself.'),
    R(52, 'easy', 'detail', 'According to the passage, why does Ilse tell customers to return on Thursday?', 'Because people do not trust a repair that is finished too quickly.', ['Because she repairs clocks only one day each week.', 'Because Thursday is the day her assistant works.', 'Because she needs several days to order replacement parts.'], 'Ilse says nobody believes a repair that takes an hour, and that on Thursday customers believe her.'),
    R(53, 'medium', 'inference', 'The passage suggests that Dev’s reaction to Ilse’s explanation about Thursdays is one of', 'private doubt that her explanation reflects real wisdom.', ['open admiration for her understanding of customers.', 'anger at being asked to wait on customers.', 'confusion about why customers return at all.'], 'Dev laughed but privately thought it was the sort of thing people say to seem wise.'),
    R(54, 'medium', 'vocabulary in context', 'As it is used in the passage, the phrase “Each part was sound” most nearly means that each part was', 'free of defects.', ['loud in operation.', 'reasonable in price.', 'healthy in appearance.'], 'The watch was not broken and Dev found nothing wrong with any piece, so each was free of defects.'),
    R(55, 'medium', 'function of a detail', 'The passage’s description of the watch losing six minutes by evening mainly serves to', 'show that a mechanism can fail even when every part appears to work.', ['prove that Dev replaced the wrong mainspring.', 'demonstrate that the carriage clock is unreliable.', 'explain why Ilse distrusts modern watches.'], 'The watch loses time although Dev finds nothing wrong, illustrating Ilse’s point that the parts are not the clock.'),
    R(56, 'medium', 'inference', 'Ilse’s challenge to Dev (“Then fix that… I will not say a word”) most nearly suggests that she', 'expects the task to teach him something that argument could not.', ['believes Dev is unable to repair the watch.', 'wants to end the conversation about the shop’s methods.', 'intends to dismiss Dev if he fails.'], 'She answers his criticism with a task rather than an argument, and afterwards guides him.'),
    R(57, 'medium', 'detail', 'According to the passage, what finally allowed Dev to correct the watch?', 'Listening for the rhythm of the watch until he noticed where it hesitated.', ['Testing each part separately with a new set of tools.', 'Replacing the watch’s mainspring a second time.', 'Comparing the watch to the carriage clock on the shelf.'], 'Ilse taught him to listen; after a week he heard a hesitation and found a burr on one tooth.'),
    R(58, 'hard', 'figurative language', 'The comparison of the watch’s hesitation to “a person catching their breath on a stair” primarily suggests that the flaw was', 'subtle and nearly human in character, noticeable only through close attention.', ['dangerous to the watch’s other parts.', 'the result of an earlier careless repair.', 'easy to detect by sight.'], 'A catch of breath is slight and lifelike, which suits a hesitation that could be heard only by careful listening.'),
    R(59, 'hard', 'character development', 'The final paragraph most strongly suggests that Dev has', 'adopted Ilse’s way of working, and Ilse recognizes it.', ['decided to leave the shop for a different job.', 'lost interest in repairing clocks.', 'begun to resent Ilse’s advice.'], 'Dev now tells a customer to return on Thursday, and Ilse smiles without looking up.'),
]

P2 = """SOCIAL SCIENCE: This passage is an original essay on the history of timekeeping.

Until the late nineteenth century, most American towns kept their own time. Clocks were set by the sun, so that noon occurred in each town at the moment the sun reached its highest point overhead. Because the sun reaches that point earlier in the east than in the west, a clock in Boston read differently from one in Albany, and Albany’s differed from Buffalo’s. For farmers and shopkeepers who rarely traveled far, these differences caused no trouble. A few minutes either way hardly mattered when the only timetable was the rising of the sun.

The railroads changed that. As train lines spread across the continent, a journey of a few hundred miles could cross a dozen local times. Each railroad set its timetables according to its own reference city, and stations where several lines met often displayed several clocks, each showing a different hour. Passengers missed connections, conductors struggled to reconcile schedules, and the confusion was not merely inconvenient but dangerous: two trains scheduled on the same track at times that seemed different to each crew could collide. By the early 1880s, the nation’s railroads were operating on dozens of separate time standards.

The solution, proposed by railroad managers, was to divide the continent into broad zones in which every clock would read the same. On November 18, 1883, often called “the day of two noons,” the railroads adopted four zones across the United States. In many towns, residents gathered at jewelers’ shops and railway stations to watch clocks be reset. Some were moved back and some forward, so that in places where clocks were turned back, the same hour was briefly counted twice. Most people adjusted with little fuss.

Not everyone approved. Some critics objected that a private industry had no right to redefine time for the public. Newspaper editors in several cities complained that the zones substituted the convenience of the railroads for the authority of the sun, and a number of towns refused for years to change their clocks, keeping two times side by side: “railroad time” for travel and “sun time” for everything else. One newspaper argued that people should not be asked to set their lives by a schedule made for trains.

Yet the practical advantages proved hard to resist. Businesses that depended on shipping or telegraph messages found standard time far easier to manage, and as more towns adopted it voluntarily, local time gradually lost its hold. Only in 1918, when Congress passed the Standard Time Act, did the federal government formally establish the zones that the railroads had created thirty-five years earlier.

Historians sometimes point to this episode as an example of how technology reshapes the habits it touches. The railroads did not simply speed up travel; they altered how ordinary people thought about time itself, shifting it from a local fact to be read in the sky to a shared convention to be kept by a clock. The change seemed trivial to those who lived through it, but it made possible a more tightly linked economy, and it set a pattern that later innovations would repeat: a convenience adopted for practical reasons becomes, over time, an assumption so familiar that no one remembers choosing it."""

Q2 = [
    R(60, 'easy', 'main idea', 'The passage as a whole is best described as an account of how', 'the needs of the railroads led to a system of standard time that eventually became universally accepted.', ['farmers and shopkeepers resisted the use of clocks.', 'Congress created time zones to prevent railroad accidents.', 'newspaper editors persuaded the public to adopt time zones.'], 'The passage moves from local time, to railroad confusion, to the 1883 zones, to resistance, to eventual acceptance.'),
    R(61, 'easy', 'detail', 'According to the passage, the railroads adopted four time zones in', '1883.', ['1918.', 'the 1870s.', 'the early 1880s, when they established dozens of standards.'], 'The third paragraph dates the railroads’ adoption of four zones to November 18, 1883. The 1918 date refers to Congress, and “the early 1880s” describes the period of confusion before the zones.'),
    R(62, 'medium', 'detail', 'According to the passage, the differing local times became dangerous because', 'two trains on the same track could be scheduled at times that seemed different to each crew.', ['conductors refused to follow the timetables of rival railroads.', 'passengers often boarded the wrong trains.', 'stations displayed too many clocks for workers to read.'], 'The second paragraph says trains scheduled at seemingly different times could collide.'),
    R(63, 'medium', 'vocabulary in context', 'As it is used in the fourth paragraph, the phrase “the authority of the sun” most nearly refers to', 'the sun’s position as the accepted basis for determining time.', ['the sun’s power to control the weather.', 'a legal ruling about local clocks.', 'the belief that the sun should be worshipped.'], 'Critics objected that zones replaced the traditional, sun-based standard with the railroads’ convenience.'),
    R(64, 'medium', 'inference', 'The passage suggests that the towns that kept “railroad time” and “sun time” side by side', 'accepted standard time for travel but resisted it for local life.', ['were the first towns to adopt standard time.', 'had no railroad service.', 'asked Congress to abolish time zones.'], 'The towns used railroad time for travel and sun time for everything else.'),
    R(65, 'medium', 'detail', 'According to the passage, when did the federal government formally establish the time zones?', 'In 1918, thirty-five years after the railroads created them.', ['In 1883, when the railroads adopted them.', 'In the early 1880s, in response to newspaper complaints.', 'In 1948, after businesses requested them.'], 'The fifth paragraph says Congress passed the Standard Time Act in 1918, thirty-five years after the railroads created the zones in 1883.'),
    R(66, 'medium', 'function of a paragraph', 'The last paragraph mainly serves to', 'place the adoption of standard time in a broader pattern of how technologies become unquestioned habits.', ['argue that the railroads acted improperly.', 'describe the economic effects of the telegraph in detail.', 'predict that new time zones will soon be needed.'], 'Historians are said to treat the episode as an example of a pattern that later innovations would repeat.'),
    R(67, 'hard', 'author’s attitude', 'The author’s attitude toward the adoption of standard time is best described as', 'analytical, recognizing both the objections to the change and its practical advantages.', ['enthusiastic, celebrating the railroads’ success.', 'disapproving, because it overrode local customs.', 'indifferent, because the change was trivial.'], 'The author reports critics’ objections, then the advantages that overcame them, without taking a side.'),
    R(68, 'hard', 'comparison', 'According to the passage, “sun time” differs from “railroad time” in that sun time', 'was based on the position of the sun in each locality.', ['was used only by the railroads.', 'was established by Congress in 1918.', 'was the same in every town.'], 'Local clocks were set so that noon occurred when the sun reached its highest point in that place.'),
]

P3 = """HUMANITIES: This passage is an original essay about hand-lettered signs.

On a brick wall in the old part of the city, above a hardware store that has changed owners four times, a faded advertisement for a vanished brand of soap still stretches across two stories. Its letters, each taller than a person, are slightly uneven. The curve of the S swells a little more on its lower half; the edges of the A lean, just perceptibly, toward the right. To a passerby these irregularities may suggest carelessness. To a sign painter, they suggest the opposite: a human hand working at a scale and speed that left no room for a ruler, making hundreds of small decisions that a machine would never have faced.

Hand-lettering was once among the most common of trades. Before printed vinyl and digital displays, nearly every shop front, delivery truck, and roadside billboard was lettered by someone with a brush and a steady arm. The best painters worked quickly, often standing on scaffolds, and they prized a quality they called “flow,” a sense that each letter was drawn in a single confident motion rather than built up from parts. Apprentices spent years learning to load a brush with exactly the right amount of paint, to pull a stroke of uniform width, and to judge by eye how much space to leave between letters so that a word looked evenly spaced even when its letters were different shapes.

That last skill, spacing, is subtler than it sounds. A mechanical ruler would put equal distances between the edges of letters, yet the result looks wrong: the gap between two straight-sided letters such as H and I appears much smaller than the gap between a round O and a diagonal A, which leaves a large patch of empty space. The painter compensates by adjusting, nudging shapes closer together or farther apart until the word reads as a steady rhythm. The adjustments are invisible when done well. They are noticed only when absent.

By the 1990s, computer-cut vinyl had made such skill seem nearly obsolete. A shop owner could order a sign online, and a plotter would cut flawless letters in minutes. Many painters closed their businesses. Yet in recent years a small revival has emerged. Customers who want a storefront to feel distinctive have sought out painters, and a number of younger artists have taken up the trade, studying old pattern books and apprenticing with the few veterans who remain.

What draws them is not nostalgia alone. Hand-painted letters carry the trace of the person who made them, and that trace seems to matter to viewers who encounter thousands of identical, machine-perfect signs each day. A faintly lopsided S can give a street its character in a way that a flawless one cannot. The painters sometimes joke that their goal is not perfection but the right imperfection, the kind that tells a passerby, without a word, that a person was here."""

Q3 = [
    R(69, 'easy', 'main idea', 'Which choice best states the main idea of the passage?', 'Hand-lettered signs reflect skills and human qualities that machine-made signs lack, and some younger artists are reviving the trade.', ['Computer-cut vinyl signs are cheaper and more reliable than hand-painted ones.', 'Sign painters are paid more than most other tradespeople.', 'Most old advertisements were painted carelessly.'], 'The passage explains the craft, its decline, and its revival because of the human trace it carries.'),
    R(70, 'easy', 'detail', 'According to the passage, sign painters used the term “flow” to describe', 'the sense that each letter was drawn in a single confident motion.', ['the smooth color of well-mixed paint.', 'the way a word moves across a wall.', 'the speed at which a painter finished a job.'], 'The second paragraph defines “flow” as a sense that each letter was drawn in a single confident motion rather than built up from parts.'),
    R(71, 'medium', 'inference', 'The passage suggests that a sign painter would view the irregularities in the old soap advertisement as', 'evidence of skilled work done by hand.', ['mistakes that should be corrected.', 'signs of a painter’s inexperience.', 'the result of damage from weather.'], 'The first paragraph says that to a painter the irregularities suggest a hand making many small decisions.'),
    R(72, 'medium', 'vocabulary in context', 'As it is used in the third paragraph, the word “compensates” most nearly means', 'makes adjustments to offset a problem.', ['pays for a service.', 'competes with another painter.', 'complains about a result.'], 'The painter nudges letters to correct the uneven look that equal spacing produces.'),
    R(73, 'medium', 'function of a paragraph', 'The third paragraph mainly serves to', 'illustrate a subtle skill by explaining why mechanical spacing fails.', ['argue that rulers should be banned from sign shops.', 'compare the shapes of different alphabets.', 'describe the training of apprentices.'], 'The paragraph explains spacing with the H, I, O, and A example, showing that equal gaps look uneven and a painter must adjust by eye.'),
    R(74, 'medium', 'detail', 'According to the passage, many sign painters closed their businesses because', 'computer-cut vinyl signs made their skills seem nearly obsolete.', ['customers preferred older styles of lettering.', 'apprentices stopped joining the trade.', 'hardware stores stopped buying signs.'], 'The fourth paragraph states that computer-cut vinyl made such skill seem nearly obsolete and that many painters then closed their businesses.'),
    R(75, 'hard', 'author’s attitude', 'The author’s attitude toward sign painters’ work is best described as', 'admiring and appreciative of its subtlety.', ['nostalgic and uncritical.', 'skeptical of its modern value.', 'detached and purely historical.'], 'The author stresses the painters’ skill, the invisible adjustments, and the value of the human trace.'),
    R(76, 'hard', 'detail', 'According to the passage, what draws younger artists to sign painting?', 'The human trace that hand-painted letters carry, which viewers value.', ['The high prices customers will pay.', 'A wish to imitate computer-cut letters.', 'The chance to work on scaffolds.'], 'The passage says the draw is not nostalgia alone but the trace of the maker.'),
    R(77, 'hard', 'structure', 'Which choice best describes the relationship between the first and last paragraphs?', 'The first presents a specific example of imperfect lettering; the last explains why such imperfection is valued.', ['The first describes a problem; the last proposes a solution.', 'The first gives a history; the last predicts the future.', 'The first praises hand-lettering; the last criticizes it.'], 'The opening uneven letters return in the last paragraph as the “right imperfection.”'),
]

P4 = """NATURAL SCIENCE: This passage is an original essay about monarch butterfly migration.

Each autumn, millions of monarch butterflies in eastern North America begin a journey that may cover three thousand miles, ending in a small number of mountain forests in central Mexico. The insects making the trip have never been there before. They are several generations removed from the butterflies that made the previous autumn’s flight, since the monarchs that hatch in summer live only a few weeks. How do creatures with brains smaller than a grain of rice find a destination none of them has seen? For much of the twentieth century, no one even knew where eastern monarchs spent the winter. The mountain forests in Mexico were identified by scientists only in the 1970s, after volunteers across the continent tagged thousands of butterflies with tiny adhesive labels and reported where the tagged insects were found.

Researchers have spent decades pursuing the answer, and part of it lies in the sun. Monarchs fly by a sun compass: they hold a steady angle to the sun’s position in the sky. But the sun moves during the day, so a butterfly that simply kept the sun at a fixed angle would gradually curve in a circle. To fly in a straight line, the butterfly must correct for the sun’s movement, and to do that it needs a clock.

In 2009, neurobiologist Steven Reppert and his colleagues reported that monarchs’ clocks are located not only in the brain but in the antennae. When the researchers covered the antennae of monarchs with a coating that blocked light from reaching the clock cells, the butterflies no longer flew consistently toward the south. Butterflies whose antennae were covered with a clear coating, which allowed light through, continued to head south. The result suggested that the antennae supply the insect with information about the time of day that the compass needs.

The sun compass cannot explain everything, however. Monarchs continue to migrate on cloudy days, when the sun is hidden, and some evidence suggests that they may also sense Earth’s magnetic field. In laboratory experiments, researchers have found that monarchs exposed to a magnetic field resembling that of the Mexican wintering grounds adjusted the direction they flew, but only when the light they received resembled daylight. Scientists therefore suspect that the butterflies’ magnetic sense is linked to light-sensitive molecules in the eye, although the mechanism remains uncertain.

Understanding how monarchs navigate matters beyond curiosity. Monarch populations have declined sharply in recent decades, and conservationists who want to protect the migration need to know which features of the landscape and climate the butterflies depend on. If the insects rely on cues that human activity can disrupt, such as light pollution or altered weather patterns, then that knowledge could shape decisions about where to preserve habitat. For the butterflies themselves, the route is a matter of instinct. For the scientists who study them, it is a puzzle that each answer only makes richer."""

Q4 = [
    R(78, 'easy', 'main idea', 'The passage is primarily concerned with', 'what researchers have learned about how monarch butterflies navigate and why that knowledge matters.', ['how monarch butterflies reproduce during the summer.', 'why monarch populations have declined in Mexico.', 'how scientists train butterflies to fly in a straight line.'], 'The passage moves from the puzzle of navigation through the sun compass and magnetic sense to its conservation relevance.'),
    R(79, 'easy', 'detail', 'According to the passage, a butterfly flying by a sun compass needs a clock because', 'the sun moves during the day, so the butterfly must correct for its changing position.', ['monarchs can fly only at certain hours.', 'the sun is hidden on cloudy days.', 'butterflies cannot see the sun without one.'], 'The second paragraph explains that because the sun moves during the day, a butterfly holding a fixed angle to it would curve in a circle, so it needs a clock to correct for the movement.'),
    R(80, 'medium', 'reasoning', 'The results of the antennae experiment suggest that', 'the antennae provide time-of-day information that the sun compass uses.', ['the clear coating made the butterflies fly faster.', 'the butterflies’ brains contain no clock cells.', 'butterflies navigate without light.'], 'Blocking light to the antennae disrupted direction, while a clear coating did not.'),
    R(81, 'medium', 'vocabulary in context', 'As it is used in the last paragraph, the word “cues” most nearly means', 'signals that guide behavior.', ['lines spoken by actors.', 'sticks used in games.', 'rules set by scientists.'], 'The insects “rely on cues” such as light or weather patterns to guide migration.'),
    R(82, 'medium', 'detail', 'According to the passage, the sun compass alone cannot explain monarch migration because', 'monarchs continue to migrate on cloudy days when the sun is hidden.', ['monarchs migrate only at night.', 'the sun compass works only in Mexico.', 'researchers have not studied the sun compass.'], 'The fourth paragraph says monarchs continue to migrate on cloudy days when the sun is hidden, which shows the sun compass is not the whole explanation.'),
    R(83, 'medium', 'function of a paragraph', 'The second paragraph mainly serves to', 'explain why a clock is necessary for navigation by the sun.', ['introduce a competing theory about magnetic fields.', 'describe the route monarchs follow each year.', 'argue that monarchs do not use the sun.'], 'It explains that a fixed angle to the moving sun would produce a circle.'),
    R(84, 'hard', 'inference', 'Which statement about the monarchs’ magnetic sense is best supported by the passage?', 'It may depend on light-sensitive molecules in the eye, but how it works is not yet known.', ['It has been shown to replace the sun compass entirely.', 'It operates only when monarchs are in Mexico.', 'It has been ruled out by laboratory experiments.'], 'The fourth paragraph says scientists suspect a link to the eye but that the mechanism is uncertain.'),
    R(85, 'hard', 'purpose of a detail', 'The statement that the traveling monarchs “have never been there before” serves mainly to', 'emphasize that the butterflies cannot have learned their route from experience.', ['suggest that the monarchs are lost.', 'show that monarchs prefer unfamiliar places.', 'argue that the forests are newly created.'], 'It sets up the question of how butterflies find a place none has seen.'),
    R(86, 'hard', 'inference', 'The final paragraph suggests that knowledge of how monarchs navigate could be useful because it', 'could help identify disruptions that conservationists might be able to reduce.', ['would allow scientists to control the direction of migration.', 'proves that monarch populations are increasing.', 'shows that human activity does not affect the monarchs.'], 'The author says that if the insects rely on cues that human activity can disrupt, the knowledge could guide habitat decisions.'),
]

PASSAGES = [(P1, Q1), (P2, Q2), (P3, Q3), (P4, Q4)]


def reading_items():
    items = []
    for text, questions in PASSAGES:
        for q in questions:
            item = dict(q)
            item['source_or_prompt'] = text
            items.append(item)
    return items
