"""SAT Reading and Writing benchmark, Module 1 (27 questions)."""
from bench_rw_common import E

M1 = [
    # ---- Craft and Structure
    E(1, 'words_in_context', 'medium', 'precise word in context',
      'When the city council first asked Lucía Romero to design a new public library, she submitted a set of _____ sketches that offered only a rough outline of the building’s shape. Only after months of community meetings did she produce later drafts specifying the materials, dimensions, and placement of every window.',
      'preliminary', ['meticulous', 'flamboyant', 'contentious'],
      'The sketches are contrasted with “later drafts” that specify details, and they offer “only a rough outline.” That makes preliminary the precise fit. Meticulous and flamboyant contradict “rough,” and nothing suggests the sketches caused disagreement.'),
    E(1, 'words_in_context', 'medium', 'precise word in context',
      'For decades, scholars assumed that the medieval chronicler’s account of the siege was largely _____: a dramatic tale embellished to flatter his patron. But when archaeologists recently uncovered charred grain stores and broken fortifications precisely where the chronicler said they would be, many historians began to reconsider how much of the account reflects real events.',
      'fabricated', ['corroborated', 'transcribed', 'abridged'],
      'The colon explains the blank: a “dramatic tale embellished to flatter his patron” is an invented account. The archaeological finds then prompt reconsideration, which confirms that scholars had doubted the account. Corroborated means confirmed, the opposite of the earlier view.'),
    E(1, 'words_in_context', 'hard', 'precise word in context',
      'Although the mayor’s proposal to rebuild the harbor district was praised by business leaders for its _____, many residents worried that the plan’s emphasis on speed left little room for the careful public review that an investment of this size demanded. At a packed hearing, several speakers asked that the vote be delayed until independent engineers could examine the designs.',
      'efficiency', ['originality', 'frugality', 'ambiguity'],
      '“Although” signals that business leaders admired something residents then worried about: the plan’s emphasis on speed. Efficiency names that quality. Frugality concerns cost, and originality and ambiguity are not tied to the speed the residents criticize.'),
    E(1, 'words_in_context', 'easy', 'precise word in context',
      'The waxy coating on the desert shrub’s leaves does more than prevent water loss. Botanist Ines Varga argues that it is _____ to the plant’s survival, because by reflecting intense sunlight it keeps the tissue cool enough to photosynthesize at midday, when neighboring plants have shut down.',
      'indispensable', ['incidental', 'conspicuous', 'decorative'],
      'The coating “does more than” prevent water loss and allows photosynthesis when others cannot, so it is essential: indispensable. Incidental and decorative suggest unimportance, and conspicuous concerns visibility.'),
    E(1, 'text_structure_purpose', 'medium', 'function of a sentence',
      'In the early 1900s, botanists assumed that the orchid’s intricate flower had evolved solely to attract pollinators. Naturalist Mei-Lin Tran was skeptical. [underlined: She noted that several orchid species bloom in dense forests where pollinators are scarce,] and she began to suspect that some of the flower’s features served a different purpose. Her later experiments showed that the lip of the flower channels rainwater away from its reproductive structures, protecting them from damage.',
      'It provides an observation that led the naturalist to question the prevailing assumption.',
      ['It offers a counterexample that disproves the naturalist’s later experimental findings.', 'It summarizes the experiments that confirmed the naturalist’s hypothesis.', 'It defines a technical term that is used throughout the passage.'],
      'The underlined clause reports what Tran noticed before her experiments; the next clause says it made her suspect a different purpose. It therefore functions as the observation that prompted her skepticism of the assumption stated earlier.',
      stem='Which choice best describes the function of the underlined portion in the text as a whole?'),
    E(1, 'text_structure_purpose', 'medium', 'main purpose',
      'The following text is adapted from a short story. At the ferry terminal, Ahn checked the departure board for the third time in ten minutes. Though the board still read “On time,” she could not stop smoothing the creases in her ticket, rehearsing the first sentence she would say to a brother she had not seen in eleven years. When the horn finally sounded across the water, she realized she had forgotten to breathe.',
      'To convey a character’s anxious anticipation as she waits to reunite with a family member.',
      ['To criticize the reliability of a ferry service.', 'To describe the history of a ferry terminal.', 'To explain why two siblings became estranged.'],
      'Ahn’s repeated checking, smoothing of her ticket, rehearsing, and forgetting to breathe all show nervous anticipation before seeing her brother. The board reads “On time,” so reliability is not criticized, and the text gives no reason for the eleven-year separation.',
      stem='Which choice best states the main purpose of the text?'),
    E(1, 'text_structure_purpose', 'hard', 'overall structure',
      'Some ecologists argue that reintroducing wolves into a region inevitably restores its forests, because wolves reduce the grazing of young trees by deer. Yet a recent review of twelve reintroduction programs complicates this account. In only five of the twelve did tree growth increase measurably, and in several of those five, changes in rainfall or fire management also occurred. The authors do not claim that wolves have no effect; they conclude that the effect is difficult to isolate.',
      'It presents a common claim and then describes evidence that qualifies the claim without rejecting it.',
      ['It proposes a hypothesis and then describes an experiment that confirms it.', 'It compares two competing explanations and endorses the second.', 'It outlines a problem and then recommends a specific policy.'],
      'The text states a popular claim, then introduces a review whose results complicate it. The final sentence explicitly says the authors do not deny a wolf effect, so the evidence qualifies rather than rejects the claim. No experiment, endorsement, or policy recommendation appears.',
      stem='Which choice best describes the overall structure of the text?'),
    E(1, 'cross_text_connections', 'medium', 'response to a claim',
      'Text 1\nAn economist argues that remote work raises productivity. Workers eliminate commutes, report fewer interruptions, and can schedule demanding tasks for the hours when they concentrate best. In several large surveys, remote employees completed more work per day than their office-based peers.\n\nText 2\nA management researcher notes that the studies supporting remote productivity mostly measure output on routine, individual tasks such as processing claims. Evidence on creative, collaborative work is thinner and less favorable, and she argues that productivity claims should be tied to the type of work being done.',
      'By conceding that remote work can raise productivity in some settings while arguing that the claim should be limited to certain types of tasks.',
      ['By arguing that commuting has no effect on worker productivity.', 'By insisting that worker productivity cannot be measured at all.', 'By agreeing that remote work improves productivity for every type of work.'],
      'The author of Text 2 accepts the evidence for routine tasks but says creative, collaborative work shows less benefit, so the claim should be scoped to the type of work. She does not dispute commuting or measurement, and she does not claim universal gains.',
      stem='Based on the texts, how would the author of Text 2 most likely respond to the claim in Text 1?'),
    # ---- Information and Ideas
    E(1, 'central_ideas', 'easy', 'main idea',
      'After the town’s only bookstore closed, a group of retirees began leaving shelves of used books outside the library entrance. Within months, teenagers, commuters, and young families were borrowing from the shelves and returning with donations of their own. The library now reports that circulation has risen and that visitors to the shelves often stay to ask for recommendations.',
      'A small, informal book-sharing effort has encouraged reading and helped bring members of the community together.',
      ['Libraries should replace bookstores in small towns.', 'Retirees are the most avid readers in the town.', 'Used books are more popular than new books.'],
      'The details show a retiree-led sharing effort that increased borrowing, brought different groups together, and led to conversation. The other choices make comparisons or recommendations the text never states.'),
    E(1, 'central_ideas', 'medium', 'main idea',
      'Astronomers once believed that the faint glow surrounding certain young stars was produced by hot dust. However, observations made with a new infrared instrument suggest that the glow may instead come from a thin disk of gas that the dust had hidden from earlier telescopes. If so, the gas may represent a previously unrecognized stage in the formation of planets, a possibility that researchers are now working to test.',
      'Recent observations suggest that a glow once attributed to dust may originate in a gas disk that could be linked to planet formation.',
      ['Infrared instruments are more reliable than the telescopes that came before them.', 'Astronomers have proved that dust plays no role in the formation of planets.', 'The glow around young stars has been explained by the discovery of a new kind of star.'],
      'The text contrasts an old belief with a new possibility and mentions its link to planet formation, while hedging with “suggest” and “if so.” Other choices overstate (“proved”), compare instruments, or invent a new kind of star.'),
    E(1, 'command_of_evidence_text', 'medium', 'support a hypothesis',
      'Art historian Noor Haddad hypothesizes that a set of undated paintings was produced by a single workshop rather than by several independent artists. She notes that all of the paintings, which were found together in a dealer’s storeroom and bear no signatures, use the same unusual shade of blue. Other scholars have suggested that the similarities reflect a shared style that was common in the city at the time, and Haddad acknowledges that her hypothesis depends on showing that the paintings share more than style.',
      'Chemical analysis shows that the blue pigment in every painting came from the same batch, a type not known to have been sold to other workshops.',
      ['The blue pigment was widely available to painters in the region during the period.', 'Several of the paintings depict the same landscape from different viewpoints.', 'Several of the paintings have been damaged by moisture.'],
      'Identical pigment from a batch not sold elsewhere points to one source, which directly supports a single workshop. Wide availability would weaken the inference, and the landscapes and moisture damage say nothing about who made the works.',
      stem='Which finding, if true, would most directly support Haddad’s hypothesis?'),
    E(1, 'command_of_evidence_text', 'hard', 'quotation that illustrates a claim',
      'Critics of Anita Reyes’s novel The Salt Road have observed that its protagonist, Maren, is torn between duty and ambition. One critic claims that Maren is reluctant to leave her village, even as the book’s plot pushes her toward the coast. According to the critic, Reyes shows this reluctance not through Maren’s speeches but through the small, practical excuses she invents whenever departure draws near.',
      '“She packed the satchel twice and unpacked it twice, each time finding another reason the mill would need her.”',
      ['“The road west was long, and the salt merchants promised good wages at the end of it.”', '“Her brother had left at sixteen and had never written.”', '“Maren studied the map until she knew every bend of the river by heart.”'],
      'Packing, unpacking, and inventing reasons to stay directly illustrate reluctance to leave. The other quotations describe the journey, her brother, or her study of the map, none of which shows hesitation.',
      stem='Which quotation from the novel most effectively illustrates the critic’s claim?'),
    E(1, 'command_of_evidence_quant', 'medium', 'use data to support a claim',
      'A sleep researcher surveyed students in grades 9 through 12 and claims that students who sleep fewer hours on school nights are more likely to report frequent daytime sleepiness.\n\n| Grade | Average sleep on school nights (hours) | Students reporting frequent daytime sleepiness |\n|---|---|---|\n| 9 | 8.4 | 18% |\n| 10 | 7.9 | 27% |\n| 11 | 7.3 | 41% |\n| 12 | 7.0 | 49% |',
      'Among 12th graders, who averaged 7.0 hours of sleep, 49% reported frequent daytime sleepiness, compared with 18% of 9th graders, who averaged 8.4 hours.',
      ['Students in grade 10 averaged 7.9 hours of sleep, and 27% reported frequent daytime sleepiness.', 'The percentage reporting frequent daytime sleepiness was 41% among 11th graders and 49% among 12th graders.', 'Average sleep decreased from 8.4 hours in grade 9 to 7.0 hours in grade 12.'],
      'The claim links less sleep to more sleepiness, so the answer needs both measures for groups with different sleep. Only the correct choice contrasts low-sleep and high-sleep groups on both. The others give one variable or a single group.',
      stem='Which choice most effectively uses data from the table to support the researcher’s claim?'),
    E(1, 'inferences', 'medium', 'logical completion',
      'Ecologists studying a mountain meadow removed a common flowering plant from several plots while leaving neighboring plots untouched. In the plots without the flowering plant, the number of bee visits to the meadow’s other species fell by nearly half. This result suggests that the removed plant _____',
      'may have helped attract bees that also visited the meadow’s other flowering species.',
      ['competed with nearby species for the attention of bees, which preferred the other flowers.', 'had no measurable effect on the activity of bees in the meadow.', 'was visited by bees only after the other species had disappeared.'],
      'Bee visits to other species dropped when the plant was gone, so the plant likely drew bees that then visited the others. The other choices contradict that drop or introduce claims about competition or timing that the data do not show.'),
    E(1, 'inferences', 'hard', 'logical completion',
      'Historians have long wondered why the city’s grain prices remained stable during the drought of 1340, when prices in neighboring cities tripled. Records show that in the preceding decade the city had built large public storehouses and required merchants to deposit a portion of each harvest in them. During the drought, the city released grain from these storehouses at fixed prices. Thus the city’s stable prices most likely resulted from _____',
      'a reserve of grain that the city had stockpiled under an earlier policy.',
      ['a decision by merchants to lower prices in order to attract buyers from neighboring cities.', 'the fact that the drought was less severe in the city than in neighboring cities.', 'the city’s decision to import grain from neighboring cities during the drought.'],
      'The storehouses, mandatory deposits, and fixed-price releases all point to a stockpile built earlier. No evidence describes merchant discounts, a milder local drought, or imports, and imports from cities with tripled prices would be unlikely.'),
    # ---- Standard English Conventions
    E(1, 'boundaries', 'easy', 'joining independent clauses',
      'After a month of review, the scholarship committee read more than two hundred essays from students across the state _____ only twelve applicants were invited to interview in person.',
      ', but', [', however', '; but', 'but,'],
      'Two independent clauses can be joined by a comma plus a coordinating conjunction. “However” is not a conjunction, so a comma alone creates a splice, and a semicolon should not be paired with “but.”'),
    E(1, 'boundaries', 'medium', 'nonessential phrases',
      'Rangers at the national park announced this week that Mount Kellan _____ is closed to climbers until spring because the upper trails remain covered in ice and the route’s fixed ropes have not yet been inspected.',
      ', the tallest peak in the northern range,', ['the tallest peak in the northern range,', ', the tallest peak in the northern range', '; the tallest peak in the northern range;'],
      'The phrase is nonessential and must be set off by a pair of commas. Missing either comma, or using semicolons, leaves the sentence incorrectly punctuated.'),
    E(1, 'boundaries', 'hard', 'colon before an explanation',
      'Jalen had spent a week rehearsing answers to every question he could imagine, but when he called his grandmother the night before his first job interview, she offered him only one piece of advice _____ arrive early.',
      ':', [';', ',', 'and'],
      'A colon can follow a complete clause to introduce an explanation. A semicolon needs a complete clause on both sides, “arrive early” alone is not one here, a comma would splice the pieces, and “and” creates an illogical construction.'),
    E(1, 'subject_verb_agreement', 'medium', 'agreement across an interruption',
      'Each of the newly discovered manuscripts, which were found in a sealed clay jar near the ancient library’s foundation, _____ now being studied by a team of conservators.',
      'is', ['are', 'were', 'have been'],
      'The subject is the singular “each,” not “manuscripts” or “which.” Singular “is” agrees and fits “now being studied.” The others are plural or the wrong tense.'),
    E(1, 'pronouns_modifiers', 'medium', 'dangling modifier',
      'During a week of fieldwork on the northern coast, a graduate student rose before sunrise each day to survey the beach. Walking along the shoreline at dawn, _____ The discovery later became the subject of a paper on coastal erosion.',
      'the researcher noticed a cluster of unusual shells.', ['the researcher’s attention was drawn to a cluster of unusual shells.', 'a cluster of unusual shells caught the researcher’s eye.', 'unusual shells were noticed by the researcher.'],
      'The opening phrase must describe the person who was walking. Only the correct choice puts “the researcher” immediately after the comma. In each other choice the subject is something that could not be walking.'),
    E(1, 'verb_tense', 'medium', 'past perfect',
      'By the time the restoration crew completed its work in 2021, the once-grand theater on Mercer Street _____ empty for nearly two decades, its marquee dark and its seats covered in dust.',
      'had stood', ['has stood', 'stands', 'will have stood'],
      '“By the time” and the past-tense “completed” place the vacancy before another past event, which requires the past perfect, “had stood.” Present and future forms conflict with the timeline.'),
    E(1, 'form_structure_sense', 'medium', 'parallel structure',
      'Each spring, the conservation program recruits volunteers from nearby towns and trains them in three tasks: to identify invasive plants, to map their spread, and _____ native species once the invaders have been removed.',
      'to restore', ['restoring', 'restoration of', 'they restore'],
      'The series is built from infinitive phrases (“to identify,” “to map”), so the last item should be “to restore.” The other choices break the parallel pattern.'),
    # ---- Expression of Ideas
    E(1, 'transitions', 'easy', 'contrast',
      'Ranchers in the region have long relied on seasonal rainfall to fill their stock ponds, a system that worked reliably for generations and required little more than periodic repairs to the earthen banks. _____ three consecutive dry winters have left many ponds nearly empty, forcing ranchers to haul water by truck.',
      'However,', ['Likewise,', 'For example,', 'Therefore,'],
      'The first sentence describes a long-standing reliable pattern; the second describes a disruption. That is a contrast, signaled by “However.”'),
    E(1, 'transitions', 'medium', 'example',
      'Many coastal towns have begun restoring oyster reefs to protect their shorelines from storm surge, since the reefs break up waves before they reach the beach and slowly build up sediment behind them. _____ a restored reef off the coast of Marlow has reduced the wave energy reaching the beach by nearly a third.',
      'For instance,', ['Nevertheless,', 'Consequently,', 'In contrast,'],
      'The second sentence gives a specific case of the general practice described in the first, so “For instance” is the logical transition.'),
    E(1, 'rhetorical_synthesis', 'medium', 'introduce a subject',
      'Notes:\n• The Loom Museum opened in 1987 in a former textile mill.\n• It houses more than 4,000 hand-woven textiles from 30 countries.\n• Its collection includes a 17th-century tapestry from Flanders.\n• The museum offers weaving workshops for visitors of all ages.',
      'Opened in 1987 in a former textile mill, the Loom Museum houses more than 4,000 hand-woven textiles from 30 countries.',
      ['The Loom Museum offers weaving workshops for visitors of all ages.', 'The museum’s collection includes a 17th-century tapestry from Flanders.', 'Many museums around the world have collections of textiles.'],
      'To introduce an unfamiliar museum, the sentence should give its basic identity: when and where it opened and what it holds. The other choices give a single feature or information that is not in the notes.',
      stem='The student wants to introduce the museum to an audience unfamiliar with it. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
    E(1, 'rhetorical_synthesis', 'medium', 'emphasize a difference',
      'Notes:\n• Dr. Ruth Alvarez studied two kinds of moss in a mountain valley.\n• Sunlit moss grew an average of 4 millimeters per month.\n• Shaded moss grew an average of 9 millimeters per month.\n• Both kinds were measured over a six-month period.',
      'Over six months, Dr. Alvarez found that shaded moss grew an average of 9 millimeters per month, more than twice the 4 millimeters per month of sunlit moss.',
      ['Dr. Alvarez measured both sunlit and shaded moss for six months.', 'Sunlit moss grew an average of 4 millimeters per month.', 'Dr. Alvarez studied two kinds of moss in a mountain valley.'],
      'The goal is a difference in growth, so the sentence must compare the two rates. Only the correct choice states both figures and their relationship; 9 is more than twice 4.',
      stem='The student wants to emphasize the difference in growth between the two kinds of moss. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
    E(1, 'rhetorical_synthesis', 'hard', 'explain an advantage',
      'Notes:\n• Researchers at the Halden Institute developed a paint that reflects 98% of sunlight.\n• Buildings painted with it stayed up to 4 degrees Celsius cooler than buildings painted with standard white paint.\n• The paint uses calcium carbonate, a common mineral, rather than titanium dioxide.\n• Titanium dioxide production is energy-intensive and expensive.\n• Cooler buildings need less air conditioning.',
      'Unlike standard white paint, which relies on energy-intensive titanium dioxide, the Halden Institute’s paint uses calcium carbonate, a common mineral, and keeps buildings up to 4 degrees Celsius cooler.',
      ['Researchers at the Halden Institute developed a paint that reflects 98% of sunlight.', 'Cooler buildings need less air conditioning, which saves energy.', 'Calcium carbonate is a common mineral used in the new paint.'],
      'The goal is an advantage over standard white paint, so the sentence must compare the two. Only the correct choice contrasts the materials and gives the cooling benefit. The others describe the new paint or cooling in general terms without the comparison.',
      stem='The student wants to explain an advantage of the new paint over standard white paint. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
]
