"""Additional hard Reading and Writing items used only for practice recovery.

These are separate from the benchmark so that recovery content is never a
question the student already answered on the diagnostic.
"""
from bench_rw_common import E

EXTRA = [
    E(None, 'words_in_context', 'hard', 'precise word in context',
      'When the composer’s last quartets premiered, critics called them _____: the harmonies seemed to wander without resolution, and audiences could find no melody to follow. Decades later, scholars demonstrated that the pieces follow a strict internal logic, which had simply been invisible to listeners who expected a conventional structure.',
      'incoherent', ['meticulous', 'sentimental', 'derivative'],
      'Critics heard wandering harmonies and no melody, which is how an incoherent piece would sound; scholars later showed a hidden logic. Meticulous and sentimental do not match the critics’ complaint, and derivative concerns originality.'),
    E(None, 'text_structure_purpose', 'hard', 'function of a sentence',
      'Conservators at a regional museum noticed that a seventeenth-century portrait was gradually darkening. Their analysis showed that an old layer of varnish was yellowing, and they recommended removing it. The museum’s board hesitated, however, because earlier cleanings of similar works had, in a few cases, removed original paint along with the varnish. [underlined: The board has asked for a trial on an unimportant corner of the canvas before any decision is made.]',
      'It describes a cautious step the board requested in response to the concern raised earlier.',
      ['It presents evidence that the conservators’ analysis was flawed.', 'It announces the board’s decision to reject the conservators’ recommendation.', 'It explains why the varnish began to darken.'],
      'The underlined sentence follows the board’s worry about damaging original paint and proposes a limited test, so its function is to show a cautious response. The board has not rejected the recommendation, and the sentence does not address the varnish’s chemistry.',
      stem='Which choice best describes the function of the underlined sentence in the text as a whole?'),
    E(None, 'cross_text_connections', 'hard', 'response to a proposal',
      'Text 1\nA city planner proposes requiring every new commercial building to include a rooftop garden. Such gardens cool the surrounding air, absorb rainwater, and extend the life of the roof beneath them, she argues, so the public benefits justify a uniform requirement.\n\nText 2\nAn economist agrees that rooftop gardens offer real benefits but notes that the cost of irrigation and maintenance varies widely with a building’s size and climate. A single mandate, he argues, would burden owners of small buildings far more than owners of large ones, and subsidies tied to measured benefits would spread the cost more fairly.',
      'By acknowledging the benefits of rooftop gardens while arguing that a mandate would unevenly burden owners and that incentives would be fairer.',
      ['By denying that rooftop gardens cool the surrounding air.', 'By agreeing that a uniform requirement is the most efficient policy.', 'By arguing that rooftop gardens should be required only on residential buildings.'],
      'The economist accepts the benefits but objects to the uniform mandate because of uneven costs, and proposes subsidies. He does not deny the cooling effect, endorse the mandate, or distinguish residential buildings.',
      stem='Based on the texts, how would the author of Text 2 most likely respond to the proposal in Text 1?'),
    E(None, 'central_ideas', 'hard', 'main idea',
      'Marine biologists surveying reefs in the Red Sea found colonies of coral that continued to thrive in water several degrees warmer than the temperatures that have bleached corals elsewhere. Genetic analysis suggests that these colonies descend from populations that migrated north thousands of years ago through an unusually warm channel. The researchers caution that the Red Sea corals cannot simply replace bleached reefs elsewhere, but they hope to learn which traits allow the corals to tolerate heat.',
      'Coral in the Red Sea that tolerates unusually warm water may offer clues about heat resistance, though it is not a ready substitute for bleached reefs.',
      ['Corals around the world are becoming more resistant to warming seas.', 'Red Sea corals should be transplanted to reefs that have bleached.', 'Genetic analysis has proved that Red Sea corals migrated through a warm channel.'],
      'The passage reports a heat-tolerant population, explains a possible origin, and stresses a limit on its use while hoping to learn its traits. The other choices overgeneralize, prescribe an action the researchers caution against, or state as proven what is only suggested.'),
    E(None, 'command_of_evidence_text', 'hard', 'support a claim',
      'A historian claims that the flood of 1894 permanently changed the town’s economy, shifting it from farming to manufacturing. She argues that the disaster destroyed so many farms that owners sold their land to people who built mills and small factories along the river.',
      'Tax records show that the number of farms declined sharply and that several new factories were registered in the five years after the flood.',
      ['The flood destroyed many buildings in the center of the town.', 'Several farms in the region were still operating in 1910.', 'Factories in neighboring towns also opened during the 1890s.'],
      'The claim concerns a shift from farms to factories after the flood. Records showing fewer farms and new factories in the following years directly support it. The other choices describe damage, survivors, or other towns, none of which tests the claim.',
      stem='Which finding, if true, would most directly support the historian’s claim?'),
    E(None, 'command_of_evidence_quant', 'hard', 'use data to support a claim',
      'A museum director claims that free admission boosts attendance even compared with the busiest paid days.\n\n| Type of day | Average visitors |\n|---|---|\n| Paid weekday | 410 |\n| Paid weekend day | 880 |\n| Free-admission Sunday | 1,340 |',
      'Free-admission Sundays averaged 1,340 visitors, more than the 880 visitors on paid weekend days.',
      ['Paid weekend days averaged 880 visitors, more than the 410 visitors on paid weekdays.', 'Free-admission Sundays averaged 1,340 visitors.', 'Weekday attendance was the lowest, at 410 visitors.'],
      'The claim compares free days with the busiest paid days, so the answer must give both figures: 1,340 against 880. The other choices omit the comparison or compare different days.',
      stem='Which choice most effectively uses data from the table to support the director’s claim?'),
    E(None, 'inferences', 'hard', 'logical completion',
      'Researchers noticed that a distant star’s brightness dips every nine days. A planet passing in front of the star could cause such a dip, but a planet would not change the star’s spectrum. Because the star’s spectrum also shifts every nine days, in step with the dips, the dips are more likely caused by _____',
      'changes in the star itself, such as a regular pulsation.',
      ['a planet that orbits the star once every nine days.', 'an instrument error that affected only one night of observation.', 'a second planet orbiting much farther from the star.'],
      'A transiting planet would dim the star without altering its spectrum. The synchronized spectral shifts point to the star itself changing. The alternatives are planets, which the spectrum argues against, or a one-night error, which conflicts with the repeating pattern.'),
    E(None, 'boundaries', 'hard', 'semicolons',
      'Volunteers planted more than two thousand seedlings along the riverbank during a single weekend in March _____ by the end of the following autumn, nearly all of them had taken root and begun to shade the water.',
      ';', [',', ':', 'but'],
      'The blank joins two independent clauses, so a semicolon is correct. A comma alone splices them, a colon does not introduce an explanation, and “but” creates a contrast the sentences do not have.'),
    E(None, 'subject_verb_agreement', 'hard', 'agreement with a long subject',
      'The committee’s recommendations, which were shaped by months of testimony from teachers, parents, and local business owners, _____ being reviewed by the school board this week before any changes to the calendar are announced.',
      'are', ['is', 'was', 'has been'],
      'The subject is the plural “recommendations,” not “committee’s” or “owners.” Only “are” agrees with it and fits “this week.”'),
    E(None, 'pronouns_modifiers', 'hard', 'dangling modifier',
      'Forecasters warned that the storm would reach the coast by midnight. Hoping to finish before it arrived, _____',
      'the crew worked through the night to secure the roof.', ['the roof was secured by the crew working through the night.', 'a rush to secure the roof kept the crew busy through the night.', 'the night was spent by the crew securing the roof.'],
      'The opening phrase describes someone who hopes, so the subject after the comma must be the crew. In the other choices the subject is the roof, a rush, or the night.'),
    E(None, 'verb_tense', 'hard', 'present perfect',
      'Since the library introduced its mobile app in 2019, the number of digital checkouts _____ every year, and staff now expect digital loans to exceed print loans by next spring.',
      'has grown', ['grew', 'had grown', 'will have grown'],
      'An action that began in 2019 and continues to the present takes the present perfect, “has grown.” The simple past and past perfect do not connect to the present, and the future perfect looks ahead.'),
    E(None, 'form_structure_sense', 'hard', 'agreement with a nearer subject',
      'Neither the lead researcher nor her assistants _____ surprised by the results, since the pilot study had pointed in the same direction and the team had already revised its expectations.',
      'were', ['was', 'is', 'has been'],
      'With “neither… nor,” the verb agrees with the nearer subject, the plural “assistants,” and the tense is past. “Was,” “is,” and “has been” are singular or the wrong tense.'),
    E(None, 'transitions', 'hard', 'result',
      'The museum’s new exhibit has drawn record crowds, and the gift shop, which was built to handle only a fraction of that traffic, has sold out of its most popular items. _____ the museum plans to double the shop’s stock and add a second checkout line.',
      'As a result,', ['Nevertheless,', 'For example,', 'Previously,'],
      'The plan to expand the shop follows from its selling out and overcrowding, which is a consequence signaled by “As a result.”'),
    E(None, 'rhetorical_synthesis', 'hard', 'emphasize scale',
      'Notes:\n• The Harbor Lights festival is held each October in Port Alder.\n• In 2023 it drew about 45,000 visitors.\n• Port Alder has a population of about 6,000.\n• The festival features lantern parades and boat races.\n• Local restaurants report their highest sales of the year during the festival.',
      'In 2023, Port Alder’s Harbor Lights festival drew about 45,000 visitors, several times the town’s population of about 6,000.',
      ['The festival features lantern parades and boat races.', 'Local restaurants report their highest sales of the year during the festival.', 'The Harbor Lights festival is held each October in Port Alder.'],
      'Scale relative to the town requires both the visitor count and the town’s population. Only the correct choice pairs them. The others describe activities, sales, or timing.',
      stem='The student wants to emphasize the scale of the festival relative to the size of the town. Which choice most effectively uses relevant information from the notes to accomplish this goal?'),
]
