# Generated by scripts/build-prep-bank.mjs. Edit quick-practice-data.js.
BANK = {
  "sat": {
    "math": [
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 2 = 14, what is x?",
        "options": [
          "2",
          "4",
          "6",
          "12"
        ],
        "answer": 1,
        "explanation": "Subtract 2: 3x = 12. Divide by 3: x = 4. Substitution gives 12 + 2 = 14."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $40. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$10",
          "$38",
          "$50",
          "$30"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 40 = 30. The discount itself is $10."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 2 = 18, what is the value of 8x?",
        "options": [
          "32",
          "4",
          "16",
          "36"
        ],
        "answer": 0,
        "explanation": "Subtract 2 to get 4x = 16. Double both sides: 8x = 32. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 24 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "26",
          "8",
          "40",
          "120"
        ],
        "answer": 2,
        "explanation": "24 ÷ 3 = 8 parts per minute. Multiply by 5 minutes to get 40 parts."
      },
      {
        "skill": "Equivalent expressions",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 2(x + 3) − 2x?",
        "options": [
          "0x + 3",
          "4x + 6",
          "0x + 6",
          "2x + 4"
        ],
        "answer": 2,
        "explanation": "Distribute 2: 2x + 6 − 2x. Combining the x terms gives 0x + 6."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 10. Three of the numbers are 4, 8, and 12. What is the fourth?",
        "options": [
          "10",
          "16",
          "24",
          "40"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 10 = 40. The three known numbers total 24, leaving 16."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 3 = 21, what is x?",
        "options": [
          "3",
          "6",
          "9",
          "18"
        ],
        "answer": 1,
        "explanation": "Subtract 3: 3x = 18. Divide by 3: x = 6. Substitution gives 18 + 3 = 21."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $60. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$15",
          "$57",
          "$75",
          "$45"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 60 = 45. The discount itself is $15."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 3 = 27, what is the value of 8x?",
        "options": [
          "48",
          "6",
          "24",
          "54"
        ],
        "answer": 0,
        "explanation": "Subtract 3 to get 4x = 24. Double both sides: 8x = 48. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 36 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "38",
          "12",
          "60",
          "180"
        ],
        "answer": 2,
        "explanation": "36 ÷ 3 = 12 parts per minute. Multiply by 5 minutes to get 60 parts."
      },
      {
        "skill": "Equivalent expressions",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 3(x + 3) − 2x?",
        "options": [
          "1x + 3",
          "5x + 9",
          "1x + 9",
          "3x + 7"
        ],
        "answer": 2,
        "explanation": "Distribute 3: 3x + 9 − 2x. Combining the x terms gives 1x + 9."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 15. Three of the numbers are 6, 12, and 18. What is the fourth?",
        "options": [
          "15",
          "24",
          "36",
          "60"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 15 = 60. The three known numbers total 36, leaving 24."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 4 = 28, what is x?",
        "options": [
          "4",
          "8",
          "12",
          "24"
        ],
        "answer": 1,
        "explanation": "Subtract 4: 3x = 24. Divide by 3: x = 8. Substitution gives 24 + 4 = 28."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $80. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$20",
          "$76",
          "$100",
          "$60"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 80 = 60. The discount itself is $20."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 4 = 36, what is the value of 8x?",
        "options": [
          "64",
          "8",
          "32",
          "72"
        ],
        "answer": 0,
        "explanation": "Subtract 4 to get 4x = 32. Double both sides: 8x = 64. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 48 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "50",
          "16",
          "80",
          "240"
        ],
        "answer": 2,
        "explanation": "48 ÷ 3 = 16 parts per minute. Multiply by 5 minutes to get 80 parts."
      },
      {
        "skill": "Equivalent expressions",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 4(x + 3) − 2x?",
        "options": [
          "2x + 3",
          "6x + 12",
          "2x + 12",
          "4x + 10"
        ],
        "answer": 2,
        "explanation": "Distribute 4: 4x + 12 − 2x. Combining the x terms gives 2x + 12."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 20. Three of the numbers are 8, 16, and 24. What is the fourth?",
        "options": [
          "20",
          "32",
          "48",
          "80"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 20 = 80. The three known numbers total 48, leaving 32."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 5 = 35, what is x?",
        "options": [
          "5",
          "10",
          "15",
          "30"
        ],
        "answer": 1,
        "explanation": "Subtract 5: 3x = 30. Divide by 3: x = 10. Substitution gives 30 + 5 = 35."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $100. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$25",
          "$95",
          "$125",
          "$75"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 100 = 75. The discount itself is $25."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 5 = 45, what is the value of 8x?",
        "options": [
          "80",
          "10",
          "40",
          "90"
        ],
        "answer": 0,
        "explanation": "Subtract 5 to get 4x = 40. Double both sides: 8x = 80. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 60 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "62",
          "20",
          "100",
          "300"
        ],
        "answer": 2,
        "explanation": "60 ÷ 3 = 20 parts per minute. Multiply by 5 minutes to get 100 parts."
      },
      {
        "skill": "Equivalent expressions",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 5(x + 3) − 2x?",
        "options": [
          "3x + 3",
          "7x + 15",
          "3x + 15",
          "5x + 13"
        ],
        "answer": 2,
        "explanation": "Distribute 5: 5x + 15 − 2x. Combining the x terms gives 3x + 15."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 25. Three of the numbers are 10, 20, and 30. What is the fourth?",
        "options": [
          "25",
          "40",
          "60",
          "100"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 25 = 100. The three known numbers total 60, leaving 40."
      },
      {
        "skill": "Desmos intersections",
        "tip": "Graph the two sides as y-expressions. Read the requested coordinate and verify it in the equation.",
        "prompt": "The graphs y = 2x + 3 and y = 7 intersect. What is the x-coordinate of their intersection?",
        "options": [
          "7",
          "2",
          "3",
          "10"
        ],
        "answer": 1,
        "explanation": "At an intersection, 2x + 3 = 7. So 2x = 4 and x = 2. In Desmos the point is (2, 7); use the x-coordinate, not 7."
      },
      {
        "skill": "Desmos intersections",
        "tip": "Graph the two sides as y-expressions. Read the requested coordinate and verify it in the equation.",
        "prompt": "The graphs y = 2x + 4 and y = 10 intersect. What is the x-coordinate of their intersection?",
        "options": [
          "10",
          "3",
          "4",
          "14"
        ],
        "answer": 1,
        "explanation": "At an intersection, 2x + 4 = 10. So 2x = 6 and x = 3. In Desmos the point is (3, 10); use the x-coordinate, not 10."
      },
      {
        "skill": "Desmos intersections",
        "tip": "Graph the two sides as y-expressions. Read the requested coordinate and verify it in the equation.",
        "prompt": "The graphs y = 2x + 5 and y = 13 intersect. What is the x-coordinate of their intersection?",
        "options": [
          "13",
          "4",
          "5",
          "18"
        ],
        "answer": 1,
        "explanation": "At an intersection, 2x + 5 = 13. So 2x = 8 and x = 4. In Desmos the point is (4, 13); use the x-coordinate, not 13."
      },
      {
        "skill": "Desmos intersections",
        "tip": "Graph the two sides as y-expressions. Read the requested coordinate and verify it in the equation.",
        "prompt": "The graphs y = 2x + 6 and y = 16 intersect. What is the x-coordinate of their intersection?",
        "options": [
          "16",
          "5",
          "6",
          "22"
        ],
        "answer": 1,
        "explanation": "At an intersection, 2x + 6 = 16. So 2x = 10 and x = 5. In Desmos the point is (5, 16); use the x-coordinate, not 16."
      },
      {
        "skill": "Desmos intersections",
        "tip": "Graph the two sides as y-expressions. Read the requested coordinate and verify it in the equation.",
        "prompt": "The graphs y = 2x + 7 and y = 19 intersect. What is the x-coordinate of their intersection?",
        "options": [
          "19",
          "6",
          "7",
          "26"
        ],
        "answer": 1,
        "explanation": "At an intersection, 2x + 7 = 19. So 2x = 12 and x = 6. In Desmos the point is (6, 19); use the x-coordinate, not 19."
      }
    ],
    "ela": [
      {
        "skill": "Transitions",
        "tip": "Name the relationship before reading the choices: contrast, cause, or continuation.",
        "prompt": "The first prototype used less energy than expected. Its battery life, _____, exceeded the team’s target. Which transition best completes the text?",
        "options": [
          "however",
          "therefore",
          "instead",
          "nevertheless"
        ],
        "answer": 1,
        "explanation": "Lower energy use causes longer battery life. “Therefore” signals that result; the other choices suggest a contrast."
      },
      {
        "skill": "Sentence boundaries",
        "tip": "Check both sides of a punctuation mark for complete sentences.",
        "prompt": "The archive opened in June _____ researchers can now consult its letters online. Which choice creates a complete, correctly punctuated sentence?",
        "options": [
          ",",
          ";",
          "and",
          "with"
        ],
        "answer": 1,
        "explanation": "Both sides can stand alone. A semicolon joins two independent clauses. A comma alone creates a comma splice, and “and” would need a comma here."
      },
      {
        "skill": "Words in context",
        "tip": "Predict a simple replacement, then check it against the whole sentence.",
        "prompt": "Although early observations seemed to support the hypothesis, later trials undermined it. As used here, “undermined” most nearly means:",
        "options": [
          "concealed",
          "expanded",
          "weakened",
          "established"
        ],
        "answer": 2,
        "explanation": "“Although” sets up a contrast with support. The later trials weakened the hypothesis."
      },
      {
        "skill": "Evidence",
        "tip": "Reject answers that go beyond the evidence, even if they sound plausible.",
        "prompt": "In a study of 120 seedlings, plants receiving six hours of light grew taller on average than plants receiving two hours. Which conclusion is best supported?",
        "options": [
          "All plants need six hours of light.",
          "More light always causes faster growth.",
          "Two hours of light prevents growth.",
          "The six-hour group was taller on average in this study."
        ],
        "answer": 3,
        "explanation": "The finding applies to these groups. It does not establish a universal rule or show that the two-hour group did not grow."
      },
      {
        "skill": "Subject–verb agreement",
        "tip": "Find the grammatical subject; ignore nouns inside interrupting phrases.",
        "prompt": "The collection of letters from several explorers _____ a detailed record of the voyage. Which choice completes the sentence correctly?",
        "options": [
          "provides",
          "provide",
          "have provided",
          "are providing"
        ],
        "answer": 0,
        "explanation": "The subject is the singular “collection,” not the plural “letters” or “explorers,” so “provides” agrees."
      },
      {
        "skill": "Rhetorical synthesis",
        "tip": "Read the requested goal first; use only notes that serve it.",
        "prompt": "Notes: Lake A is 40 meters deep. Lake B is 65 meters deep. Both lakes contain freshwater. The student wants to emphasize a difference in depth. Which sentence best achieves that goal?",
        "options": [
          "Both lakes contain freshwater.",
          "Lake B is 25 meters deeper than Lake A.",
          "Lake A and Lake B are both lakes.",
          "Lake B is a freshwater lake 65 meters deep."
        ],
        "answer": 1,
        "explanation": "65 − 40 = 25. Only this choice directly compares the lakes’ depths."
      },
      {
        "skill": "Inference",
        "tip": "Prefer the narrow conclusion the text supports over an absolute claim.",
        "prompt": "A museum moved a fragile manuscript into a dimmer gallery after conservators observed fading on its pages. What does the text most strongly suggest?",
        "options": [
          "The manuscript will never fade again.",
          "All other galleries were closed.",
          "The move was intended to limit further damage.",
          "The museum planned to stop displaying manuscripts."
        ],
        "answer": 2,
        "explanation": "The sequence connects observed fading with a protective change. It supports the intention to reduce damage, not a guarantee or a broader museum policy."
      },
      {
        "skill": "Sentence boundaries",
        "tip": "Check for a complete clause on each side.",
        "prompt": "The telescope captured a faint signal _____ the team repeated the observation. Which punctuation correctly joins the clauses?",
        "options": [
          ";",
          ",",
          ": because",
          "without"
        ],
        "answer": 0,
        "explanation": "Both clauses are complete. A semicolon joins them; a comma alone cannot."
      },
      {
        "skill": "Sentence boundaries",
        "tip": "A colon follows a complete clause and introduces an explanation, example, or list.",
        "prompt": "The team needed three supplies _____ paper, tape, and string. Which punctuation best completes the sentence?",
        "options": [
          ",",
          ":",
          ";",
          "."
        ],
        "answer": 1,
        "explanation": "The complete clause introduces a list of the three supplies, so a colon fits. The list cannot stand alone after a semicolon or period."
      },
      {
        "skill": "Transitions",
        "tip": "Decide whether the second statement supports, contrasts with, or results from the first.",
        "prompt": "The route was longer than expected. _____, the hikers arrived before sunset. Which transition fits?",
        "options": [
          "For example",
          "Therefore",
          "Nevertheless",
          "Similarly"
        ],
        "answer": 2,
        "explanation": "Arriving early despite a longer route is a contrast. Nevertheless expresses that contrast."
      },
      {
        "skill": "Transitions",
        "tip": "Name the logical connection before choosing a transition.",
        "prompt": "The city added protected bike lanes. _____, the share of commuters cycling to work increased. Which transition most clearly presents the increase as a result?",
        "options": [
          "Consequently",
          "Instead",
          "Nevertheless",
          "For instance"
        ],
        "answer": 0,
        "explanation": "Consequently explicitly presents the increase as a result, as the question requests."
      },
      {
        "skill": "Evidence",
        "tip": "Choose the narrow claim directly supported by the text.",
        "prompt": "A survey found that 36 of 60 students in one class preferred morning study sessions. Which statement is supported?",
        "options": [
          "All students study best in the morning.",
          "A majority of the surveyed class preferred morning sessions.",
          "Morning study improves every student’s score.",
          "Exactly 36 students in the entire school study in the morning."
        ],
        "answer": 1,
        "explanation": "36 of 60 is a majority of this surveyed class. The survey establishes preference, not effectiveness or school-wide behavior."
      },
      {
        "skill": "Evidence",
        "tip": "Separate measured results from claims about their cause.",
        "prompt": "A library recorded 400 visits in April and 500 in May. Which claim do these records support?",
        "options": [
          "A new advertising campaign caused the change.",
          "Visits will continue to rise every month.",
          "May had 100 more visits than April.",
          "Every visitor borrowed a book."
        ],
        "answer": 2,
        "explanation": "500 minus 400 is 100. The records do not explain causes, future trends, or borrowing."
      }
    ]
  },
  "act": {
    "math": [
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 5 = 35, what is x?",
        "options": [
          "5",
          "10",
          "15",
          "30"
        ],
        "answer": 1,
        "explanation": "Subtract 5: 3x = 30. Divide by 3: x = 10. Substitution gives 30 + 5 = 35."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $100. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$25",
          "$95",
          "$125",
          "$75"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 100 = 75. The discount itself is $25."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 5 = 45, what is the value of 8x?",
        "options": [
          "80",
          "10",
          "40",
          "90"
        ],
        "answer": 0,
        "explanation": "Subtract 5 to get 4x = 40. Double both sides: 8x = 80. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 60 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "62",
          "20",
          "100",
          "300"
        ],
        "answer": 2,
        "explanation": "60 ÷ 3 = 20 parts per minute. Multiply by 5 minutes to get 100 parts."
      },
      {
        "skill": "Math · Distribution",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 5(x + 3) − 2x?",
        "options": [
          "3x + 3",
          "7x + 15",
          "3x + 15",
          "5x + 13"
        ],
        "answer": 2,
        "explanation": "Distribute 5: 5x + 15 − 2x. Combining the x terms gives 3x + 15."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 25. Three of the numbers are 10, 20, and 30. What is the fourth?",
        "options": [
          "25",
          "40",
          "60",
          "100"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 25 = 100. The three known numbers total 60, leaving 40."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 6 = 42, what is x?",
        "options": [
          "6",
          "12",
          "18",
          "36"
        ],
        "answer": 1,
        "explanation": "Subtract 6: 3x = 36. Divide by 3: x = 12. Substitution gives 36 + 6 = 42."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $120. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$30",
          "$114",
          "$150",
          "$90"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 120 = 90. The discount itself is $30."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 6 = 54, what is the value of 8x?",
        "options": [
          "96",
          "12",
          "48",
          "108"
        ],
        "answer": 0,
        "explanation": "Subtract 6 to get 4x = 48. Double both sides: 8x = 96. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 72 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "74",
          "24",
          "120",
          "360"
        ],
        "answer": 2,
        "explanation": "72 ÷ 3 = 24 parts per minute. Multiply by 5 minutes to get 120 parts."
      },
      {
        "skill": "Math · Distribution",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 6(x + 3) − 2x?",
        "options": [
          "4x + 3",
          "8x + 18",
          "4x + 18",
          "6x + 16"
        ],
        "answer": 2,
        "explanation": "Distribute 6: 6x + 18 − 2x. Combining the x terms gives 4x + 18."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 30. Three of the numbers are 12, 24, and 36. What is the fourth?",
        "options": [
          "30",
          "48",
          "72",
          "120"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 30 = 120. The three known numbers total 72, leaving 48."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 7 = 49, what is x?",
        "options": [
          "7",
          "14",
          "21",
          "42"
        ],
        "answer": 1,
        "explanation": "Subtract 7: 3x = 42. Divide by 3: x = 14. Substitution gives 42 + 7 = 49."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $140. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$35",
          "$133",
          "$175",
          "$105"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 140 = 105. The discount itself is $35."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 7 = 63, what is the value of 8x?",
        "options": [
          "112",
          "14",
          "56",
          "126"
        ],
        "answer": 0,
        "explanation": "Subtract 7 to get 4x = 56. Double both sides: 8x = 112. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 84 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "86",
          "28",
          "140",
          "420"
        ],
        "answer": 2,
        "explanation": "84 ÷ 3 = 28 parts per minute. Multiply by 5 minutes to get 140 parts."
      },
      {
        "skill": "Math · Distribution",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 7(x + 3) − 2x?",
        "options": [
          "5x + 3",
          "9x + 21",
          "5x + 21",
          "7x + 19"
        ],
        "answer": 2,
        "explanation": "Distribute 7: 7x + 21 − 2x. Combining the x terms gives 5x + 21."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 35. Three of the numbers are 14, 28, and 42. What is the fourth?",
        "options": [
          "35",
          "56",
          "84",
          "140"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 35 = 140. The three known numbers total 84, leaving 56."
      },
      {
        "skill": "Backsolve",
        "tip": "Substitute a promising answer into the original equation; check both sides.",
        "prompt": "If 3x + 8 = 56, what is x?",
        "options": [
          "8",
          "16",
          "24",
          "48"
        ],
        "answer": 1,
        "explanation": "Subtract 8: 3x = 48. Divide by 3: x = 16. Substitution gives 48 + 8 = 56."
      },
      {
        "skill": "Percent multipliers",
        "tip": "A percent decrease multiplies by 1 minus the decimal rate. Do not subtract the rate itself.",
        "prompt": "A jacket costs $160. Its price is reduced by 25%. What is the sale price?",
        "options": [
          "$40",
          "$152",
          "$200",
          "$120"
        ],
        "answer": 3,
        "explanation": "Keep 75% of the price: 0.75 × 160 = 120. The discount itself is $40."
      },
      {
        "skill": "Read the target",
        "tip": "Circle what the question actually asks. You may not need to solve for the variable.",
        "prompt": "If 4x + 8 = 72, what is the value of 8x?",
        "options": [
          "128",
          "16",
          "64",
          "144"
        ],
        "answer": 0,
        "explanation": "Subtract 8 to get 4x = 64. Double both sides: 8x = 128. You do not need to calculate x."
      },
      {
        "skill": "Rate setup",
        "tip": "Write the units with the numbers so they cancel in the right direction.",
        "prompt": "A machine produces 96 parts in 3 minutes at a constant rate. How many parts does it produce in 5 minutes?",
        "options": [
          "98",
          "32",
          "160",
          "480"
        ],
        "answer": 2,
        "explanation": "96 ÷ 3 = 32 parts per minute. Multiply by 5 minutes to get 160 parts."
      },
      {
        "skill": "Math · Distribution",
        "tip": "Distribute to every term, then combine like terms. Check with a simple input if uncertain.",
        "prompt": "Which expression is equivalent to 8(x + 3) − 2x?",
        "options": [
          "6x + 3",
          "10x + 24",
          "6x + 24",
          "8x + 22"
        ],
        "answer": 2,
        "explanation": "Distribute 8: 8x + 24 − 2x. Combining the x terms gives 6x + 24."
      },
      {
        "skill": "Average shortcut",
        "tip": "Convert an average to a total before finding the missing value.",
        "prompt": "Four numbers have an average of 40. Three of the numbers are 16, 32, and 48. What is the fourth?",
        "options": [
          "40",
          "64",
          "96",
          "160"
        ],
        "answer": 1,
        "explanation": "The total is 4 × 40 = 160. The three known numbers total 96, leaving 64."
      }
    ],
    "ela": [
      {
        "skill": "English · Concision",
        "tip": "Choose the shortest option that preserves the full meaning and correct grammar.",
        "prompt": "Choose the most concise replacement for “returned back again” in: After lunch, Maya returned back again to the laboratory.",
        "options": [
          "returned",
          "returned back",
          "went and returned back",
          "returned again back"
        ],
        "answer": 0,
        "explanation": "“Returned” already expresses going back. The other choices repeat the same idea."
      },
      {
        "skill": "English · Agreement",
        "tip": "Cross out the phrase between the subject and verb in your head.",
        "prompt": "Choose the correct verb: The results of the experiment _____ consistent across three trials.",
        "options": [
          "was",
          "is",
          "were",
          "has been"
        ],
        "answer": 2,
        "explanation": "“Results” is plural. “Of the experiment” does not change the subject, so “were” is correct."
      },
      {
        "skill": "Reading · Detail",
        "tip": "Locate the exact evidence before relying on what you remember.",
        "prompt": "Lena had planned to photograph the harbor at dawn. Thick fog concealed the boats, so she spent the morning sketching the nearby market instead. Why did Lena change her plan?",
        "options": [
          "The market opened early.",
          "Fog blocked her view of the boats.",
          "Her camera was broken.",
          "The harbor was closed."
        ],
        "answer": 1,
        "explanation": "The passage explicitly states that thick fog concealed the boats. The other explanations are not given."
      },
      {
        "skill": "English · Organization",
        "tip": "Use pronouns and time markers to find the sentence’s anchor.",
        "prompt": "A paragraph begins: (1) Noor collected water samples from three ponds. (2) She then compared their acidity. (3) The results revealed a clear difference. Where should “Each sample was placed in a labeled container” go?",
        "options": [
          "Before sentence 1",
          "After sentence 3",
          "After sentence 2",
          "After sentence 1"
        ],
        "answer": 3,
        "explanation": "The samples must first be collected; labeling them logically precedes comparing their acidity. “Each sample” refers back to sentence 1."
      },
      {
        "skill": "Reading · Purpose",
        "tip": "Ask what a detail does for the passage, not just what it says.",
        "prompt": "The old station once handled hundreds of travelers each day. Now, weeds push through its platform, and the ticket windows stand empty. The details about weeds and empty windows primarily:",
        "options": [
          "explain train schedules",
          "suggest the station’s decline",
          "describe a recent renovation",
          "criticize travelers"
        ],
        "answer": 1,
        "explanation": "The details contrast former activity with present disuse and emphasize decline."
      },
      {
        "skill": "English · Punctuation",
        "tip": "An introductory dependent clause needs a comma before the main clause.",
        "prompt": "Choose the correct punctuation: Although the trail was steep _____ the hikers reached the summit before noon.",
        "options": [
          ",",
          ";",
          ":",
          "."
        ],
        "answer": 0,
        "explanation": "“Although the trail was steep” is a dependent clause. A comma separates it from the independent main clause."
      },
      {
        "skill": "Reading · Inference",
        "tip": "Separate a reasonable inference from a claim the passage cannot prove.",
        "prompt": "At rehearsal, Eli paused before a difficult passage. After practicing it slowly several times, he played the entire piece without stopping. What is best supported?",
        "options": [
          "Eli had never played the instrument.",
          "The piece had no difficult passages.",
          "Focused practice helped Eli perform more fluently.",
          "Eli will never make another mistake."
        ],
        "answer": 2,
        "explanation": "His performance became continuous after targeted practice. The passage supports that improvement without sweeping claims."
      },
      {
        "skill": "English · Concision",
        "tip": "Remove repeated meaning without removing necessary information.",
        "prompt": "Choose the most concise replacement for “cooperated together” in: The two teams cooperated together on the mural.",
        "options": [
          "cooperated",
          "jointly cooperated together",
          "together cooperated jointly",
          "cooperated with one another together"
        ],
        "answer": 0,
        "explanation": "Cooperated already conveys working together. The added words are redundant."
      },
      {
        "skill": "English · Concision",
        "tip": "Keep the action and remove duplicate time markers.",
        "prompt": "Choose the most concise replacement for “at this current point in time”: At this current point in time, the bridge is closed.",
        "options": [
          "At this moment in the current time",
          "Now",
          "At this time currently",
          "In the present current moment"
        ],
        "answer": 1,
        "explanation": "Now expresses the same present-time meaning clearly and concisely."
      },
      {
        "skill": "English · Agreement",
        "tip": "Ignore the phrase between the subject and verb.",
        "prompt": "The box of old maps _____ on the top shelf. Which verb completes the sentence?",
        "options": [
          "are",
          "were",
          "is",
          "have been"
        ],
        "answer": 2,
        "explanation": "The singular subject is box, not maps. Is agrees with box."
      },
      {
        "skill": "English · Agreement",
        "tip": "Identify the subject before choosing the verb.",
        "prompt": "The musicians in the final row _____ ready to perform. Which choice is correct?",
        "options": [
          "is",
          "was",
          "has been",
          "are"
        ],
        "answer": 3,
        "explanation": "Musicians is plural, so are agrees. The phrase in the final row does not change the subject."
      },
      {
        "skill": "Reading · Detail",
        "tip": "Find the explicit cause in the passage.",
        "prompt": "Omar usually walked to school. On Tuesday, a broken sidewalk blocked his usual route, so he took the bus. Why did Omar take the bus?",
        "options": [
          "His usual route was blocked.",
          "He woke up late.",
          "He disliked walking.",
          "The weather was cold."
        ],
        "answer": 0,
        "explanation": "The passage names the blocked sidewalk as the reason. The other explanations are not stated."
      },
      {
        "skill": "Reading · Detail",
        "tip": "Return to the exact sentence rather than guessing from context.",
        "prompt": "The volunteers sorted books in the morning and repaired shelves after lunch. Before leaving, they swept the floor. What did they do immediately after lunch?",
        "options": [
          "Swept the floor",
          "Sorted books",
          "Repaired shelves",
          "Bought new books"
        ],
        "answer": 2,
        "explanation": "The passage explicitly says they repaired shelves after lunch."
      }
    ]
  }
}
