BEGIN;
ALTER TABLE paths ADD COLUMN IF NOT EXISTS learning_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS adaptive_meta TEXT NOT NULL DEFAULT '{}';
ALTER TABLE sprint_questions ADD COLUMN IF NOT EXISTS adaptive_meta TEXT NOT NULL DEFAULT '{}';
ALTER TABLE lesson_steps ADD COLUMN IF NOT EXISTS adaptive_meta TEXT NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS learning_hints (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL, source TEXT NOT NULL, source_id TEXT NOT NULL, hint_count INTEGER NOT NULL DEFAULT 0, UNIQUE (user_id, source, source_id));
ALTER TABLE learning_hints ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_hints FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mentics_owner ON learning_hints;
CREATE POLICY mentics_owner ON learning_hints TO mentics_app USING (user_id=mentics_current_user_id()) WITH CHECK (user_id=mentics_current_user_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON learning_hints TO mentics_app;
GRANT USAGE, SELECT ON SEQUENCE learning_hints_id_seq TO mentics_app;
CREATE TABLE IF NOT EXISTS adaptive_tracks (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL, track_key TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 2, benchmark_session_id INTEGER, benchmark_completed_at TEXT, diagnostic TEXT NOT NULL DEFAULT '{}', generation_token TEXT, generation_started DOUBLE PRECISION, generation_error TEXT, UNIQUE (user_id, track_key));
ALTER TABLE adaptive_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE adaptive_tracks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mentics_owner ON adaptive_tracks;
CREATE POLICY mentics_owner ON adaptive_tracks TO mentics_app USING (user_id=mentics_current_user_id()) WITH CHECK (user_id=mentics_current_user_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON adaptive_tracks TO mentics_app;
GRANT USAGE, SELECT ON SEQUENCE adaptive_tracks_id_seq TO mentics_app;
CREATE TABLE IF NOT EXISTS adaptive_sessions (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL, track_key TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'generating', request_key TEXT NOT NULL, questions TEXT NOT NULL DEFAULT '[]', answers TEXT NOT NULL DEFAULT '{}', hint_usage TEXT NOT NULL DEFAULT '{}', profile_snapshot TEXT NOT NULL DEFAULT '{}', summary TEXT NOT NULL DEFAULT '{}', generation_note TEXT, created_at DOUBLE PRECISION NOT NULL, updated_at DOUBLE PRECISION NOT NULL, UNIQUE (user_id, request_key));
ALTER TABLE adaptive_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE adaptive_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mentics_owner ON adaptive_sessions;
CREATE POLICY mentics_owner ON adaptive_sessions TO mentics_app USING (user_id=mentics_current_user_id()) WITH CHECK (user_id=mentics_current_user_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON adaptive_sessions TO mentics_app;
GRANT USAGE, SELECT ON SEQUENCE adaptive_sessions_id_seq TO mentics_app;
CREATE TABLE IF NOT EXISTS learning_events (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL, track_key TEXT NOT NULL, source TEXT NOT NULL, source_id TEXT NOT NULL, skill_key TEXT NOT NULL, subskill TEXT NOT NULL, domain TEXT NOT NULL, difficulty TEXT NOT NULL, is_correct BOOLEAN NOT NULL, response_ms INTEGER, hint_count INTEGER NOT NULL DEFAULT 0, confidence INTEGER, misconception TEXT, evidence TEXT NOT NULL DEFAULT '{}', created_at DOUBLE PRECISION NOT NULL, UNIQUE (user_id, source, source_id));
ALTER TABLE learning_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mentics_owner ON learning_events;
CREATE POLICY mentics_owner ON learning_events TO mentics_app USING (user_id=mentics_current_user_id()) WITH CHECK (user_id=mentics_current_user_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON learning_events TO mentics_app;
GRANT USAGE, SELECT ON SEQUENCE learning_events_id_seq TO mentics_app;
CREATE TABLE IF NOT EXISTS path_generations (id BIGSERIAL PRIMARY KEY, user_id INTEGER NOT NULL, track_key TEXT NOT NULL, request_key TEXT NOT NULL, status TEXT NOT NULL, profile_snapshot TEXT NOT NULL, task_ids TEXT NOT NULL DEFAULT '[]', note TEXT, created_at DOUBLE PRECISION NOT NULL, UNIQUE (user_id, request_key));
ALTER TABLE path_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE path_generations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mentics_owner ON path_generations;
CREATE POLICY mentics_owner ON path_generations TO mentics_app USING (user_id=mentics_current_user_id()) WITH CHECK (user_id=mentics_current_user_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON path_generations TO mentics_app;
GRANT USAGE, SELECT ON SEQUENCE path_generations_id_seq TO mentics_app;
CREATE INDEX IF NOT EXISTS idx_learning_events_profile ON learning_events(user_id, track_key, created_at);
CREATE INDEX IF NOT EXISTS idx_adaptive_session_resume ON adaptive_sessions(user_id, track_key, kind, status);
UPDATE paths SET is_active=FALSE WHERE category='Test Prep' AND is_user_added=FALSE AND learning_version<2;
COMMIT;
